### ISSUE TITLE
Forward EditText autocorrection attributes (and the textbox itself!)

### ISSUE THREAD

**Issue by shusain93** [stfalcon-studio/ChatKit#1]
MessageInput is nice however the lack of proper capitalization and no way to fix it with gradle on is infuriating! Could you make the EditText object of the input public?

**Comment by troy379** [comment]
Hello @shusain93 !
It was a small oversight, you shouldn't come into a infuriating because of this :)
Please, upgrade the library version to `0.1.2`. Now EditText and "submit" button is protected and have getters.
I've also added `textCapSentences` in MessageInput by default.
