### ISSUE TITLE
incoming vs outcoming

### ISSUE THREAD

**Issue by op27no2** [stfalcon-studio/ChatKit#101]
Ok I must be missing something in the instructions/sample.

How do you set whether a message is incoming vs outcoming before adding it to the adapter?

Thanks!

**Comment by remy554** [comment]
Same here

**Comment by remy554** [comment]
I just found how it works : 
When you create your adapter, the first parameter "senderId" has to be the same id that contains the Author object used as the Sender

**Comment by a-pool** [comment]
@remy554 can you show me how to make it works ? i just want to know how to make it right or left. thank you so much.

**Comment by op27no2** [comment]
Ok, so it works like this - when you create your adapter you give it a tag that is used to subsequently designate a message as 'self' so that it shows up on the self side.

CustomMessageListAdapter<Message> adapter = new CustomMessageListAdapter<>("SELF_TAG", imageLoader);

Message mMes2 = new Message("SELF_TAG", mUser2, "message");
adapter.addToStart(mMes2, true);

Message mMes1 = new Message("NOT_SELF", mUser1, "message2");
adapter.addToStart(mMes1, true);

**Comment by tusharuit25** [comment]
//0 for self message update message id if you successfully send it to server
Message mMes2 = new Message("0", mUser2, "message");
adapter.addToStart(mMes2, true);
//message id for others
Message mMes1 = new Message(mssageid, mUser1, "message2");
adapter.addToStart(mMes1, true);

**Comment by troy379** [comment]
Glad you've figured it out! :)

**Comment by chnouman** [comment]
@tusharuit25  this not working for me.

**Comment by ramtintk** [comment]
@tusharuit25 not working, only the colors change, but they stay on the same side

**Comment by tusharuit25** [comment]
//0 for self message update message id if you successfully send it to server at the place of userid inside your message model
