### ISSUE TITLE
How can I show avater on messages I sent?

### ISSUE THREAD

**Issue by freundyotam** [stfalcon-studio/ChatKit#107]
How can I show avater on messages I sent? It seems like that even if the user object contains avatar string it still not showing on messageList.

**Comment by aalap03** [comment]
Try using `MessageHolders` class and use .`setOutcomingTextConfig(holder, layoutResourceId) `

**Comment by bevzaanton** [comment]
You have to create your own layout and ViewHolder. After that you will be able to show any data what you want. [How to do it](https://github.com/stfalcon-studio/ChatKit/blob/master/docs/COMPONENT_MESSAGES_LIST.md#create-your-own-layout)
