### ISSUE TITLE
Style Message Outcoming

### ISSUE THREAD

**Issue by KAIOAVILA** [stfalcon-studio/ChatKit#108]
![screen shot 2017-11-07 at 18 22 40](https://user-images.githubusercontent.com/2415473/32515899-abd8b13e-c3e8-11e7-80f6-5013f626360f.png)
Hello, I'm using a very long message in the chat and it's running out of color in the bubble, the message is out.

Example Message:

> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce eget interdum mauris. Pellentesque ultricies felis et cursus molestie. Nam luctus massa in tortor pellentesque, eget volutpat nisi interdum. Etiam ac volutpat tortor, vitae pellentesque tortor. Sed nec enim non sem tempor maximus. Integer arcu felis, ornare fringilla efficitur nec, ornare vel nulla. Morbi sollicitudin imperdiet bibendum. Sed condimentum, lectus at pretium hendrerit, elit lacus vestibulum odio, sit amet iaculis sem massa lobortis urna. Proin blandit arcu dolor, et hendrerit turpis dictum id. Integer blandit, urna quis laoreet faucibus, nulla tellus tincidunt lacus, id feugiat velit turpis sed nunc. Proin malesuada vulputate urna, ut malesuada turpis euismod sed.
> 
> Duis hendrerit ante vitae purus eleifend, in mattis arcu sodales. Integer mollis ex eu sodales dictum. Proin sit amet ultricies arcu, sed efficitur massa. Ut ut dui vitae ligula viverra elementum. Nulla id lectus neque. Vestibulum feugiat lectus eu tortor sollicitudin vehicula. Donec ut metus ut ex pellentesque egestas vitae vitae arcu. Morbi sed est at turpis hendrerit venenatis ac at odio. In auctor dapibus neque, eu malesuada nisl pellentesque et. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
> 
> Pellentesque hendrerit orci nec libero eleifend, et posuere ex interdum. Ut laoreet eu lorem et tempor. Sed felis sapien, sagittis vitae faucibus eget, hendrerit vel justo. Sed dapibus nec tellus at dapibus. Ut interdum mollis lacinia. Pellentesque gravida lacus arcu, at vestibulum nunc varius ut. Nulla lacinia bibendum nisi quis sollicitudin. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc accumsan eu dui vitae tincidunt. Etiam a faucibus magna. Cras vel consequat metus. Interdum et malesuada fames ac ante ipsum primis in faucibus.
> 
> Vivamus non lacus massa. Sed vitae massa nec ex pellentesque pharetra ut vel sem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed et nisi in nunc interdum laoreet in ac orci. Proin ut bibendum neque. Ut id felis id risus porta ornare nec a nisl. Pellentesque arcu ante, tempor nec velit et, sagittis auctor purus. Mauris sed nisi convallis, elementum sem et, lobortis tortor. Maecenas viverra varius enim id ullamcorper. Nam tristique sapien quis lorem vulputate, a pellentesque nisl tincidunt. Vivamus eu est venenatis elit rhoncus aliquet. In sed finibus nulla. Fusce justo eros, maximus vitae consequat vitae, consectetur at quam. Aliquam pellentesque dolor sit amet urna egestas gravida.
> 
> Sed a magna a neque porta ultricies in at turpis. Nulla feugiat eros vel velit suscipit, scelerisque rutrum libero tincidunt. Nullam convallis enim sed lectus vulputate mollis. Duis nec tellus dignissim, luctus risus sed, consequat urna. Pellentesque ut urna eu eros porttitor mollis sit amet elementum est. Vivamus nec purus in nibh fringilla egestas a vitae leo. Mauris feugiat turpis rhoncus dolor sollicitudin aliquam. Morbi congue felis quis laoreet eleifend. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam libero turpis, elementum et tellus eu, fermentum placerat purus. In sit amet u

**Comment by bevzaanton** [comment]
Hi @KAIOAVILA ! Thank you for your bug report. This issue fixed in version 0.3.0
