### ISSUE TITLE
Outcoming is not probably the correct name.

### ISSUE THREAD

**Issue by sadegh** [stfalcon-studio/ChatKit#110]
Thank for the great library.

I just wanted to mention that the name for `OutcomingMessage` is not correct, and you probably wanted to use **`Outgoing`** instead of `Outcoming`

**Comment by anymol** [comment]
We will correct the name in the new version of the library. =)

**Comment by mtangoo** [comment]
@anymol any ETA?

**Comment by troy379** [comment]
Hi @sadegh  @mtangoo 
Sorry, but our team has decided that this naming is mostly correct (if you wish you can check [this link](https://wikidiff.com/outgoing/outcoming) out 😉)

Btw, the new version of the library has came out!
