### ISSUE TITLE
holderConfig is deprecated than how can i show sender name in group chat

### ISSUE THREAD

**Issue by shahviral9990** [stfalcon-studio/ChatKit#111]

**Comment by sourabhz** [comment]
You got any solution or not ?

**Comment by troy379** [comment]
Hi @shahviral9990 @sourabhz 
Please, see the [migration log](https://github.com/stfalcon-studio/ChatKit/blob/master/docs/MIGRATION_GUIDE.MD) for more info

Best regards, Alex
