### ISSUE TITLE
How to add the text of who send the message like below ?

### ISSUE THREAD

**Issue by sayami007** [stfalcon-studio/ChatKit#114]
![24281854_679455235576394_847574535_o](https://user-images.githubusercontent.com/12579109/33467403-5f4f80a8-d67c-11e7-8b0f-0737b322cdc9.jpg)

**Comment by alexkrolinfinum** [comment]
Hi @sayami007 
You can find how to achieve this [here](https://github.com/stfalcon-studio/ChatKit/blob/master/docs/COMPONENT_MESSAGES_LIST.md#not-enough-features-create-your-own-holder)

**Comment by troy379** [comment]
Hi @sayami007 
You can find how to achieve this [here](https://github.com/stfalcon-studio/ChatKit/blob/master/docs/COMPONENT_MESSAGES_LIST.md#not-enough-features-create-your-own-holder)
