### ISSUE TITLE
How to add image and text in the same message?

### ISSUE THREAD

**Issue by radwasherif** [stfalcon-studio/ChatKit#115]
I would like to add an image and a caption line below it.

**Comment by alouanemed** [comment]
You can achieve that by creating your own custom viewholder.
an example can be found here : [CustomOutcomingTextMessageViewHolder](https://github.com/stfalcon-studio/ChatKit/blob/c6bb4adf7eeeebf3058ba62a5d1c987a42ef8a90/sample/src/main/java/com/stfalcon/chatkit/sample/features/demo/custom/holder/holders/messages/CustomOutcomingTextMessageViewHolder.java)

**Comment by radwasherif** [comment]
As far as I understood, the design is still for one type per message.

**Comment by bevzaanton** [comment]
@alouanemed is right. You can display any data in your custom layout by creating your own custom viewholder.
