### ISSUE TITLE
I manage to add Location, Video to this chatKit

### ISSUE THREAD

**Issue by ChiHwe** [stfalcon-studio/ChatKit#116]
For those who suffer to using this chakKit : 

I am a developer who using stfalcon Chatkit to develop my Chatting interface, 

and i manage to play-around with this chatkit and add-on new feature, example like: add Video, add Location. 
all you need to do is: read these file: 

item_custom_incoming_voice_message.xml (layout, change your own layout, example, you want video, then put a imageview with play button infront )  
item_custom_outcoming_voice_message.xml(same) 
IncomingVoiceMessageViewHolder
OutcomingVoiceMessageViewHolder 

in your chat layout main file, link above together with contenttype, example like below(what i done in my project) : 
 private void initAdapter() {

        MessageHolders holdersConfig = new MessageHolders()
                .registerContentType(
                        CONTENT_TYPE_VOICE,
                        IncomingVideoMessageViewHolder.class,
                        R.layout.item_custom_incoming_video_message,
                        OutcomingVideoMessageViewHolder.class,
                        R.layout.item_custom_outcoming_video_message,
                        this)
                .registerContentType(
                        CONTENT_TYPE_LOCATION,
                        IncomingLocationMessageViewHolder.class,
                        R.layout.item_custom_incoming_location_message,
                        OutcomingLocationMessageViewHolder.class,
                        R.layout.item_custom_outcoming_location_message,
                        this)
                .setIncomingTextLayout(R.layout.item_custom_incoming_text_message)
                .setOutcomingTextLayout(R.layout.item_custom_outcoming_text_message)
                .setIncomingImageLayout(R.layout.item_custom_incoming_image_message)
                .setOutcomingImageLayout(R.layout.item_custom_outcoming_image_message);

        super.messagesAdapter = new MessagesListAdapter<>(super.senderId, holdersConfig, super.imageLoader);
        super.messagesAdapter.setOnMessageLongClickListener(this);
        super.messagesAdapter.setOnMessageViewClickListener(this);
        //super.messagesAdapter.setLoadMoreListener(this);
        super.messagesAdapter.setOnMessageClickListener(this);
        //super.messagesAdapter.enableSelectionMode(this); if enable it will cause the copy function not working
        messagesList.setAdapter(super.messagesAdapter);

    }

on message click in the chat activity : 

@Override
    public  void onMessageViewClick(View view, Message message){
 if (message.getLocationurl() != null){
            Intent intent = new Intent(android.content.Intent.ACTION_VIEW);
            intent.setData(Uri.parse(message.getLocationurl()));
            startActivity(intent);
        }

 if (message.getVideourl() != null ) {
            Intent intent = new Intent(android.content.Intent.ACTION_VIEW);
            intent.setDataAndType(Uri.parse(message.getVideourl()), "video/*");
            startActivity(Intent.createChooser(intent, "Play video..."));
        }
}

i am suffered for few days and managed to get it done:

![photo_2017-12-04_11-09-09](https://user-images.githubusercontent.com/24539251/33534655-d5923346-d8e3-11e7-981e-bfd6177f48f3.jpg)

**Comment by tusharuit25** [comment]
well done mate, please share location adding code too just for an idea !

**Comment by ChiHwe** [comment]
Hi, 
the idea is : register content type for location, 
then link the location api with it, 

when user click on the share location, open goole map, 
once receive the location from google map, 
close the google map and display the location image in the chat room.

**Comment by tusharuit25** [comment]
thank you mate for your kind revert and sharing of idea .... I will try to implement it but please promise me to help it with little code snippets if possible ....!

**Comment by ChiHwe** [comment]
Hi buddy, sure, i will, if you encounter any problem, you may let me know, and don worry, since i able to made it, you can too : )

**Comment by talhahafeez88** [comment]
Hi ChiHwe
following your footsteps, I have added two types but every time IncomingVideoMessageViewHolder is calling.  

Is there anything to do with MessageContentType interface?

**Comment by namanmehta1997** [comment]
@ChiHwe How do you check wheather a message should be shown as Video or MapView or something else?

**Comment by bfjfm2** [comment]
@ChiHwe  How to add **List Type** Message, like ChatBot interface?

**Comment by tusharuit25** [comment]
@ChiHwe completed every type that we were expecting thanks bro !!!

**Comment by ChiHwe** [comment]
hi tusharuit25, you managed to get it done ? if so, congratulation !!

**Comment by ChiHwe** [comment]
hi talhahafeez88, Sorry for reply you late, i hope you have fixed your problem above, but if not, for my opinion, i think you have done something incorrectly so that the chatkit always detact the same viewholder, maybe you define some naming duplicate, please check again

**Comment by ChiHwe** [comment]
hi bfjfm2, can you provide some code and explanation ? i  am not very sure what you asking. thanks

**Comment by rlee1990** [comment]
Is there a tutorial for this. I made the holders and the layout files but setting everything else up has me lost.

**Comment by ShoubhikBanerjee** [comment]
Could you please share a code snippet , for IncomingLocationMessageViewHolder.class,???

**Comment by BenjaminDTA** [comment]
Hi there, is it possible to have a sample of your xml layout item_custom_incoming_video_message and IncomingVideoMessageViewHolder.class. 

I have issue to define the registerContentType() method

Thanks a lot

**Comment by tusharuit25** [comment]
https://github.com/stfalcon-studio/ChatKit/issues/116 checkout @BenjaminDTA

**Comment by BenjaminDTA** [comment]
Hi there,

Thanks for reply @tusharuit25 

I have managed to display text message and image message with chatkit ui, but still have issues with videos.

I still not understand how can i define my own ViewHolder class (here : IncomingVideoMessageViewHolder.class and OutcomingVideoMessageViewHolder.

My holdersConfig is set like this : 

`        holdersConfig = new MessageHolders()
                .setIncomingTextLayout(R.layout.item_custom_incoming_text_message)
                .setOutcomingTextLayout(R.layout.item_custom_outcoming_text_message);
`

Any clues for an Android's beginner ? :D
