### ISSUE TITLE
Attachment pressed color is not working

### ISSUE THREAD

**Issue by dengue8830** [stfalcon-studio/ChatKit#117]
i have setted this attributes for the pressed state and not working when i pressed the attachment button (keeps the gray default bg)
```
        app:showAttachmentButton="true"
        app:attachmentButtonDefaultBgPressedColor="@color/colorPrimary"
        app:attachmentButtonDefaultIconColor="@color/primary_text"
        app:attachmentButtonDefaultIconPressedColor="@color/white"
```

I am missing something? have you an working example? I tried your demo on playstore but there is no example for this case

**Comment by troy379** [comment]
Hi @dengue8830
Have you tried to add `attachmentButtonDefaultBgColor`? Can't say what's the problem from glance but also have no time to debug now, sorry.

Let me know if it works please
