### ISSUE TITLE
hello i have problem using chatkit

### ISSUE THREAD

**Issue by idotalmor** [stfalcon-studio/ChatKit#118]
hello
i am new to android development and i didn't understand how to use this library.
i have an array list of users (i wrote my own users class containing userid name last name etc..)
i also have an sql with tables for each user messages. (i am writing messaging app with only 2 users msg option)
my question is how do i take the users and present them in dialog adapter list?
i figure that i need to make some soft of list array of objects containing user id and last msg and so on, and then connect the list to the dialog adapter.
can anyone give me an example of dialog list adapter which is working? with static data inside?
any help will be appreciated 
all the samples in this site are not working when opening them in android studio and it is very difficult to figure out how to use this library

**Comment by troy379** [comment]
The sample is working well, so if you have some problems importing the project - please check the StackOverflow for possible answers
