### ISSUE TITLE
DialogsList in reverse mode

### ISSUE THREAD

**Issue by ezefire** [stfalcon-studio/ChatKit#12]
Using the dialogs list I saw that dialogs were added at the bottom and reversed. So I looked for the issue and I found that in the setAdapter() method from the DialogsList class you are setting the layoutManager with the "reverseLayout" flag as true. Is that ok?

**Comment by matheusleite** [comment]
Same thing here. How I set the dialogs to the top-bottom?

**Comment by uaeuae** [comment]
Anyone was able to set Messages to the top-bottom?

**Comment by troy379** [comment]
Hi there!
In version `0.2.1` we've added overloaded `setAdapter` method in `DialogsList` and `MessagesList`, with which you can set reverse mode to `false`.

Best regards, Alexander.

**Comment by shusain93** [comment]
Oddly this introduces a bizarre bug in my application where sometimes it would reverse and other times it wouldn't. Setting reverse mode false just solved it all the time.
