### ISSUE TITLE
Emoji

### ISSUE THREAD

**Issue by kostasoft** [stfalcon-studio/ChatKit#121]
Hello!
How to integrate a Emoji (for example: https://github.com/hani-momanii/SuperNova-Emoji) into the ChatKit?

**Comment by ozanurkn** [comment]
hi, i am waiting for response?

**Comment by sadaq19** [comment]
I managed to integrate Hanni's supernova emoji in my chatkit.
The only way I found is by downloading the two library and integreate them manually. I mean copy them from their "com" folder to the "com" folder of your project (copy paste into android studio by right cliking on the "com" package level of your project).
I mean by "com folder", the first folder you find in the java folder of your project.
You have to add all others files required by the libraries.
Then finally use custom holders for incoming and ongoing message. By doing this, you will be able to edit xml file of messages (replace Textview by EmojieTextView and replace InputText (editText for text entering) by EmojieEditText.
You must follow carefully integration's tuto of each library and you will easily succed to merge the two library.
At the end, you'll have chatKit plus SuperNova emojie into it

**Comment by bevzaanton** [comment]
You no need to copy ChatKit and other libraries files. You can just create your own layout and ViewHolder([How to do it](https://github.com/stfalcon-studio/ChatKit/blob/master/docs/COMPONENT_MESSAGES_LIST.md#create-your-own-layout)). In this layout you can use any views instead TextView(EmojieTextView for example). And in your custom ViewHolder you need to describe the rules of displaying data in layout.
