### ISSUE TITLE
Dates must not be null

### ISSUE THREAD

**Issue by Oirere-Jr** [stfalcon-studio/ChatKit#125]
On loading the message activity, I get an error : "Dates must not be null"

**Comment by alanraso** [comment]
@Oirere-Jr 
Maybe your `IMessage` implementations classes has some `null` value on `getCreatedAt()` method. If that's the case, the [DateFormatter](https://github.com/stfalcon-studio/ChatKit/blob/c6bb4adf7eeeebf3058ba62a5d1c987a42ef8a90/chatkit/src/main/java/com/stfalcon/chatkit/utils/DateFormatter.java) class throws this exception.

**Comment by troy379** [comment]
@Oirere-Jr You should pass the valid `createdAt` inside the `getCreatedAt()` method implementation
