### ISSUE TITLE
chatkit sdk support kotlin

### ISSUE THREAD

**Issue by karthik-github** [stfalcon-studio/ChatKit#126]

**Comment by bevzaanton** [comment]
Do you any problems with integration ChatKit with kotlin?

**Comment by brandon-haugen** [comment]
@bevzaanton, I have been using ChatKit with Kotlin for the last 6 months at least with no problems.

Maybe @karthik-github wanted to know if there was going to be a pure Kotlin implementation of ChatKit?

**Comment by troy379** [comment]
Nevertheless, I think this have no reasons for this at all. Closing this one
