### ISSUE TITLE
inputMaxLines doesn't work

### ISSUE THREAD

**Issue by SamuelMarks** [stfalcon-studio/ChatKit#127]
Following your docs, I tried:

    app:inputMaxLines="1"

[e.g.: in `activity_custom_holder_messages.xml`]

So I hacked together this solution for my purposes:

    mChatInput2 = findViewById(R.id.activity_room_chat_input2);
    final EditText inputEditText = mChatInput2.getInputEditText();
    inputEditText.setImeOptions(KeyEvent.ACTION_DOWN);
    inputEditText.setImeActionLabel("DONE", KeyEvent.KEYCODE_ENTER);
    inputEditText.setOnKeyListener(new View.OnKeyListener() {
        @Override
        public boolean onKey(View v, int keyCode, KeyEvent event) {
            if (event != null
                    && event.getAction() == KeyEvent.ACTION_DOWN
                    && keyCode == KeyEvent.KEYCODE_ENTER){
                mChatInput2.getButton().performClick();
                return true;
            }
            return false;
        }
    });
    mChatInput2.setInputListener(new MessageInput.InputListener() {
        @Override
        public boolean onSubmit(CharSequence input) {
            Log.d("onSubmit", input.toString());
            return true;
        }
    });

As you can see, I'm trying to get the "enter" button to work also.

**Comment by bevzaanton** [comment]
Attribute app:inputMaxLines just duplicates android:maxLines attribute of EditText. The attribute maxLines corresponds to the maximum height of the EditText, it controls the outer boundaries and not inner text lines.
https://stackoverflow.com/questions/7092961/edittext-maxlines-not-working-user-can-still-input-more-lines-than-set
