### ISSUE TITLE
Set padding for custom content message. 

### ISSUE THREAD

**Issue by stshelton** [stfalcon-studio/ChatKit#128]
Is it possible to change the padding for just a custom content message? I see you can do it to all of the messages thru styling the messageList in XML but I want to change the padding for just the custom content message I created.

**Comment by anymol** [comment]
No it isn't. You can set the [padding](https://github.com/stfalcon-studio/ChatKit/blob/0987b4d676a0f7ea6742abe67ec4439eef36a2e2/docs/COMPONENT_MESSAGES_LIST.md#styling-via-attributes) for incoming and outcoming messages at all but set the padding for custom content type you can't.

**Comment by troy379** [comment]
Hi @stshelton 
Currently it's not possible to change the content of default messages' layouts. For this purposes please create your own layout. [Here's how to do this](https://github.com/stfalcon-studio/ChatKit/blob/master/docs/COMPONENT_MESSAGES_LIST.md#create-your-own-layout)
