### ISSUE TITLE
findViewById within a MessageListAdapter

### ISSUE THREAD

**Issue by teslazero** [stfalcon-studio/ChatKit#13]
When i use "MessageListAdapter<IMessage>".setOnMessageClickListener into the 
onMessageClick i would like to get the View which i suppose it's a TextView 
from the MessageListAdapter object by using the findViewbyId method.
What i'm missing its how do i get the View id that i should pass to findViewById method ?!?

The thing i need to do is to change the color of a part of the text dynamically and that's why i need the TextView.

**Comment by troy379** [comment]
Hello @teslazero !

To get access to views in message items you need to create your own holders (for both incoming and outcoming) which must be extended from `IncomingMessageViewHolder` and `OutcomingMessageViewHolder` respectively. Than you will have an access to protected fields (in this case - TextView) and will have ability to change its behavior in `onBind(Message message)` method.

And don't forget to register your holders via `HoldersConfig` object:

```
MessagesListAdapter.HoldersConfig holdersConfig = new MessagesListAdapter.HoldersConfig();
holdersConfig.setIncomingHolder(CustomIncomingMessageViewHolder.class);
holdersConfig.setOutcomingHolder(CustomOutcomingMessageViewHolder.class);;
adapter = new MessagesListAdapter<>(senderId, holdersConfig, imageLoader);
```

P.S. Looking ahead, i can assume that you want to linkify your messages. If it's true - you can wait a few days for a new library version, where we already implemented this features

Best regards, Alexander
