### ISSUE TITLE
Change Date Header behaviour / frequency 

### ISSUE THREAD

**Issue by andreluizreis** [stfalcon-studio/ChatKit#130]
I would like to know if there is any way to change the frequency of the Date Header? Now, I think it is per day. I would like to have every ten minutes. 

The solution, for now, is to create my own message with the date. However, I can not remove the default date header. Only, if I do a hack.

**Comment by bevzaanton** [comment]
Unfortunately, ChatKit does not provide such functionality. We have plans to add this functionality in the future but If you have some ideas will be great if you do it and create pull request.
