### ISSUE TITLE
kotlin.KotlinNullPointerException

### ISSUE THREAD

**Issue by emadph** [stfalcon-studio/ChatKit#135]
ava.util.concurrent.TimeoutException

    private static final String INSTANCE_LOCATOR = "v1:us1:dc4e0506-ea28-4fcb-a27e-6278e1188315";
    private static final String TOKEN_PROVIDER_ENDPOINT = "tokenProvider";
    private static final String USER_ID = "ep_ahk";

**Comment by troy379** [comment]
@emadph What's this? How does this related to ChatKit?

**Comment by mradzinski** [comment]
@troy379 I don't think this is related to ChatKit at all. Have been using it with Kotlin for 8 or 9 months already and never faced a NPE caused by ChatKit itself.

**Comment by troy379** [comment]
@mradzinski Yea, the provided code snippet looks weird and not related to the library obviously. Closing this one
