### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by jonisak** [stfalcon-studio/ChatKit#14]
Is it possible to add images? Send photo from camera? Or is it only text messaging that is supported?

Best regards
Björn

**Comment by troy379** [comment]
Hello @jonisak !

Yes, it possible right now (in v.0.1.2) via custom view holder object ([see here](https://github.com/stfalcon-studio/ChatKit/blob/master/docs/COMPONENT_MESSAGES_LIST.md#not-enough-features-create-your-own-holder) )
But I would advise you to wait just a few days for library update, where we have added default logic for images.

Best regards, Alexander

**Comment by jonisak** [comment]
Hi Alexander,

Thank you! ChatKit looks great.

Will you update the example project as well?

Best regards
Björn @jonisak

**Comment by troy379** [comment]
Thank you for your feedback!
Of course we will. Moreover - it will have its own documentation 😉

**Comment by jonisak** [comment]
Great!
I look forward to take a look at it! :)  Will it come this week?

**Comment by troy379** [comment]
Yep :)

**Comment by jonisak** [comment]
Fantastic!

**Comment by jonisak** [comment]
How does it look? Close to a release?

**Comment by troy379** [comment]
Hello @jonisak !
Version `0.2.0` is finally out :)

You can see how to use default images [here](https://github.com/stfalcon-studio/ChatKit/blob/master/docs/COMPONENT_MESSAGES_LIST.md#adding-image-message), and how to add custom content types [here](https://github.com/stfalcon-studio/ChatKit/blob/master/docs/COMPONENT_MESSAGES_LIST.md#custom-content-types).

Also, don't forget to check out the [changelog](https://github.com/stfalcon-studio/ChatKit/blob/master/docs/CHANGELOG.md).

Best regards, Alexander

P.S. There is no demo images in docs yet, but they'll appear soon. Nevertheless, sample app is already updated :) Have a nice weekend!

**Comment by jonisak** [comment]
Awsome!

Thank you!



Skickat från min iPhone
