### ISSUE TITLE
MessagesList and Messages to support Spanned String (hyperlinking works in messages)

### ISSUE THREAD

**Issue by Arun4rangan** [stfalcon-studio/ChatKit#141]
Hey is there a way to currently to hyperlink words in messages to website/url?
https://stackoverflow.com/questions/2734270/how-do-i-make-links-in-a-textview-clickable

**Comment by dmathewwws** [comment]
@Arun4rangan did you find an answer to this question?

**Comment by Arun4rangan** [comment]
You could used message `CustomMessageViewHolder` and create a scannable text on `onBind` and attach it to textView as textView takes in both String, spannableString and spannableBuilder. 

Hope that helps

**Comment by XavierGomez95** [comment]
> You could used message `CustomMessageViewHolder` and create a scannable text on `onBind` and attach it to textView as textView takes in both String, spannableString and spannableBuilder.
> 
> Hope that helps

Thank you so much! :D
