### ISSUE TITLE
Unread messages in MessagesList

### ISSUE THREAD

**Issue by SoNep** [stfalcon-studio/ChatKit#142]
How I can show unread messages in  MessagesList?

**Comment by bevzaanton** [comment]
Hi @adamvar . You have to create your own layout and ViewHolder. After that you will be able to show any data what you want. [How to do it](https://github.com/stfalcon-studio/ChatKit/blob/master/docs/COMPONENT_MESSAGES_LIST.md#create-your-own-layout)
