### ISSUE TITLE
LoadMore Feauture is missing from Dialogs List?

### ISSUE THREAD

**Issue by WajidAli007** [stfalcon-studio/ChatKit#145]
Hi,
I was wondering if Dialogs-list has something for lazy loading (pagination). As the messages list adapter has. I wold like to contribute if it don't have already. But I just wanted if there is already some shortcut then I should avoid reinventing the wheel.

**Comment by BlueSeph28** [comment]
I think there is no lazy loading implemented, I managed to do that using the view as RecyclerView.

```
dialogsList.addOnScrollListener(object: RecyclerView.OnScrollListener() {
            override fun onScrollStateChanged(recyclerView:RecyclerView, newState:Int) {
                super.onScrollStateChanged(recyclerView, newState)
                if (!recyclerView.canScrollVertically(1) && !loading)
                    loadMore(LOAD_COUNT, offset)
            }
        })
```
Inside loadMore I added the new dialogs with addItem function

> adapter.addItem(DIALOG dialog) - adds one dialog to the end of the list

and updated the list like a recyclerView with **adapter.notifyDataSetChanged()**

**Comment by rossica** [comment]
Thanks for the code snippet @BlueSeph28 !
I was just about to open an issue for this as I need this feature as well.
But, the ScrollListener will have to suffice for now.
