### ISSUE TITLE
Bug On Chatkit: "Add/Send" files Option On Default View not working

### ISSUE THREAD

**Issue by gutzygwin** [stfalcon-studio/ChatKit#148]
#### Expected behavior
Chatkit app is an open source andriod application which are flexible components for chat UI implementation. Some users mistaken this application for a communication app.  It doesn't suppport communicating with other people. It basically a **demo** which provides everything a chat app requires and serves as a tool kit for such trivial task as chat. Chatkit can perform as many functions as a normal chatting app should do, text writing, sharing of emoticons, etc.

#### Actual behavior
However, upon click-on the **add/sendFiles** when in default view, it doesn't respond. "Other tools for chatting such as texting,  sending emojis are functioning except trying to click this function below(see illustration below).

![Screenshot_20180319-141303.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521465613/lu6poqhunsbadyc6bhhv.png)
 

#### How to reproduce
* Download Chatkit from Google playstore. 
* Open the application and select default view templates. 
* try texting and clicking on the **add/send** files. 
* ***Add/send files Not responding***

--------------------------------------------------------

* Version of the app: 1.0
* last updated : April 12, 2017.

--------------------------------------------------------

* Browser: Google playstore/ Chatkit
* Operating system: Android 7.0

#### Recording Of The Bug

https://youtu.be/JH9OyTLp1rE
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@gutzygwin/bug-on-chatkit-add-send-files-option-not-working">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by bevzaanton** [comment]
@gutzygwin Thanks for your bug report. We have fixed it in v0.2.3.
