### ISSUE TITLE
Custom inputButtonBackground for different states?

### ISSUE THREAD

**Issue by delta9** [stfalcon-studio/ChatKit#15]
Is it possible to add a custom drawable for different states?

In "[selector_bg_send.xml](https://github.com/stfalcon-studio/ChatKit/blob/master/chatkit/src/main/res/drawable/selector_bg_send.xml)" I see:

`    <item android:drawable="@drawable/mask" android:state_enabled="false" />`
` <item android:drawable="@drawable/mask_active" android:state_enabled="true" />`

But we are only able to set a static custom drawable using "app:inputButtonBackground".

I'd like to simply change the colour of the default purple background when it is active to blue.

Thanks for your help, love ChatKit!

**Comment by delta9** [comment]
Ah after reading more about Drawable Resources I figured it out - sorry!

**Comment by troy379** [comment]
Hello @delta9 !
Now, in version `0.2.0` you can change default shape colors of "submit" button via `inputButtonDefaultBgColor` for **normal** state, `inputButtonDefaultBgPressedColor ` for **pressed** and `inputButtonDefaultBgDisabledColor` attributes.

You can also check out other new attributes [here](https://github.com/stfalcon-studio/ChatKit/blob/master/docs/STYLES_ATTR.md#messageinput-xml-attributes)

Best regards, Alexander.

**Comment by delta9** [comment]
Hey Alexander,

Thank you so much for the quick updates, v0.2 looks amazing.

Have a lovely weekend!

Kind regards,

Melvin
