### ISSUE TITLE
How to change typface in item_incoming_text_message.xml

### ISSUE THREAD

**Issue by iman2420** [stfalcon-studio/ChatKit#150]
Hi. i want to change typeface in this textView:
     
`<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginBottom="8dp"
        android:layout_marginLeft="16dp"
        android:layout_marginRight="16dp"
        android:layout_marginTop="8dp">

        <com.stfalcon.chatkit.utils.ShapeImageView
            android:id="@id/messageUserAvatar"
            android:layout_width="40dp"
            android:layout_height="40dp"
            android:layout_alignParentBottom="true"
            android:layout_marginEnd="8dp"
            android:layout_marginRight="8dp" />

        <com.google.android.flexbox.FlexboxLayout
            android:id="@id/bubble"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginEnd="@dimen/message_incoming_bubble_margin_right"
            android:layout_marginRight="@dimen/message_incoming_bubble_margin_right"
            android:layout_toEndOf="@id/messageUserAvatar"
            android:layout_toRightOf="@id/messageUserAvatar"
            android:orientation="vertical"
            app:alignContent="stretch"
            app:alignItems="stretch"
            app:flexWrap="wrap"
            app:justifyContent="flex_end">

            <TextView 
                android:id="@id/messageText"                 // This TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content" />

            <TextView
                android:id="@id/messageTime"              // This TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_below="@id/messageText"
                android:layout_marginLeft="8dp"
                android:layout_marginStart="8dp"
                app:layout_alignSelf="center" />

        </com.google.android.flexbox.FlexboxLayout>

    </RelativeLayout>`

How to do it?

**Comment by iman2420** [comment]
No any idea?

**Comment by IvanKalabanan** [comment]
@iman2420 you can create your own layout for incoming/outcoming messages
Like that 
`MessagesListAdapter.HoldersConfig holdersConfig = new MessagesListAdapter.HoldersConfig();
holdersConfig.setIncomingLayout(R.layout.item_custom_incoming_message);
holdersConfig.setOutcomingLayout(R.layout.item_custom_outcoming_message);
adapter = new MessagesListAdapter<>(senderId, holdersConfig, imageLoader);`
