### ISSUE TITLE
How to set click listener to dialog items?

### ISSUE THREAD

**Issue by Fkut** [stfalcon-studio/ChatKit#151]

**Comment by andreluizreis** [comment]
You need to create your own messageHolder class like the examples. Inside the class, you can call your listener.

**Comment by anymol** [comment]
@andreluizreis was right.
You need to implement your own [holder](https://github.com/stfalcon-studio/ChatKit/blob/0987b4d676a0f7ea6742abe67ec4439eef36a2e2/docs/COMPONENT_MESSAGES_LIST.md#not-enough-features-create-your-own-holder) and implement your own interface with listener.
