### ISSUE TITLE
ChatKit active or deprecated?

### ISSUE THREAD

**Issue by daniellfalcao** [stfalcon-studio/ChatKit#153]
Is this library still active? or will it be deprecated? I'm asking because it's been a little over a year since the library received an update.

**Comment by andreluizreis** [comment]
I am using this library for a long time and I think it is deprecated. No one is answering the issues here.

**Comment by mtangoo** [comment]
@andreluizreis what about forking and maintain a fork?

**Comment by mtangoo** [comment]
BTW I checked forks and seems there is active fork maintained by @m0d
https://github.com/m0d/ChatKit/tree/develop

**Comment by BlueSeph28** [comment]
Yes, I'm interested too if there is a way to contribute to this, I want it to contribute, this is a good library

**Comment by mtangoo** [comment]
@blueSeph28
Looking at pending PR i will presume either author have no time for nowbor have silently abandoned the library.

I would suggest that you fix issues and provide PR to the active Fork. In future this library can easily import changes from the fork.

**Comment by alexz89ua** [comment]
Hi guys! Sorry for long time silence...  our team is are really proud of ChatKit. We can`t leave this project, so we decided to find more time for it between of our commercial projects and continue to work on ChatKit. We have new ideas and also we will review your PRs. Thanks for your work!
In several weeks we will resume development. 
Stay in touch :wink:

**Comment by andreluizreis** [comment]
Thanks, @alexz89ua for the good news.

**Comment by mtangoo** [comment]
Good news indeed

**Comment by troy379** [comment]
🎉
