### ISSUE TITLE
Setting side of message on chat window

### ISSUE THREAD

**Issue by leonch79** [stfalcon-studio/ChatKit#155]
Hi Great library. Does anyone know how do you set the left side or right side of the chat window for the message depending on the user?

**Comment by brandon-haugen** [comment]
Whether messages are displayed on the left or right hand side of the chat window is controlled by the Author of the Message object.

You can take a look at the doc for the MessageList component [here](https://github.com/stfalcon-studio/ChatKit/blob/0987b4d676a0f7ea6742abe67ec4439eef36a2e2/docs/COMPONENT_MESSAGES_LIST.md).

**Comment by anymol** [comment]
Hi. In the [description](https://github.com/stfalcon-studio/ChatKit/blob/0987b4d676a0f7ea6742abe67ec4439eef36a2e2/docs/COMPONENT_MESSAGES_LIST.md#custom-content-types) to the ViewHolder it is indicated: 
> the adapter itself recognizes and processes incoming and outcoming message types
