### ISSUE TITLE
Problem with appcompat.

### ISSUE THREAD

**Issue by JorgeRiveiro** [stfalcon-studio/ChatKit#156]
I try use this library but when i implement the library in my build.gradle(app) with `implementation 'com.github.stfalcon:chatkit:0.2.2'` and sync i get this error in the appcompat(`implementation 'com.android.support:appcompat-v7:27.1.1'`):

All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 27.1.1, 26.1.0. Examples include com.android.support:animated-vector-drawable:27.1.1 and com.android.support:support-media-compat:26.1.0 

Someone can help me with this problem? I don't want to change the version of target devices.
Thanks!

**Comment by brandon-haugen** [comment]
This most likely isn't an issue with ChatKit itself, it sounds like you are mixing versions of the support libraries in your build.gradle

Here is a snippet from the app I work on that is using ChatKit and the support libraries

> implementation 'com.android.support:appcompat-v7:27.1.1'
> implementation 'com.android.support:support-v4:27.1.1'
> implementation 'com.android.support:design:27.1.1'
> implementation 'com.android.support:support-vector-drawable:27.1.1'
> implementation 'com.android.support.constraint:constraint-layout:1.1.0'
> implementation 'com.android.support:gridlayout-v7:27.1.1'
> implementation 'com.android.support:recyclerview-v7:27.1.1'
> implementation 'com.github.stfalcon:chatkit:0.2.2'

Check to make sure all of the support libraries in your build.gradle are using the same version numbers. The error message seems to indicate that there is a dependency on **com.android.support:support-media-compat:26.1.0** that should be updated to version 27.1.1

ChatKit does not depend on version 26.1.0 of the support libraries, it depends internally on 25.3.1 (see [here](https://github.com/stfalcon-studio/ChatKit/blob/master/chatkit/build.gradle)) which is not a version number the error message complains about.

**Comment by bevzaanton** [comment]
We have updated support_version to 27.1.1 in ChatKit version 0.2.3
