### ISSUE TITLE
You can't set adapter to MessagesList. Use #setAdapter(MessagesListAdapter) instead

### ISSUE THREAD

**Issue by veeresh1456** [stfalcon-studio/ChatKit#157]
here is my code for main_activity.

public class MainActivity extends AppCompatActivity implements MessageInput.InputListener {

    private final String senderId = "0";
    private ImageLoader imageLoader;
    private MessagesListAdapter<Message> messagesAdapter;
    private MessagesList messagesList;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        this.messagesList = (MessagesList) findViewById(R.id.messagesList);

        imageLoader = new ImageLoader() {
            @Override
            public void loadImage(ImageView imageView, String url) {
                Picasso.get().load(url).into(imageView);
            }
        };

        initAdapter();

        MessageInput input = (MessageInput) findViewById(R.id.input);
        input.setInputListener(this);
    }

    @Override
    public boolean onSubmit(CharSequence input) {
        this.messagesAdapter.addToStart(new Message(){}, true);
        return true;
    }

    private void initAdapter() {
        this.messagesAdapter = new MessagesListAdapter<Message>(this.senderId, null);
        this.messagesList.setAdapter(messagesAdapter);
    }
}
![untitled](https://user-images.githubusercontent.com/11258936/41060972-cabeb6e6-69ee-11e8-8d5d-0e19fbc2d095.png)

**Comment by brandon-haugen** [comment]
@veeresh1456, it looks like your IDE/code is using the wrong version of `setAdapter()` on `messagesList`.

If you look at the code for `MessagesList`, you will see that there are 3 different `setAdapter()` methods defined. The one that takes an `Adapter` is not the one you want to use as it is just going to throw an exception (see [here](https://github.com/stfalcon-studio/ChatKit/blob/3ca0aa530de3ab92938dfe76cf0839a0fd24d4be/chatkit/src/main/java/com/stfalcon/chatkit/messages/MessagesList.java#L54)).

If the IDE is getting in the way, use the two-argument version (see [here](https://github.com/stfalcon-studio/ChatKit/blob/3ca0aa530de3ab92938dfe76cf0839a0fd24d4be/chatkit/src/main/java/com/stfalcon/chatkit/messages/MessagesList.java#L77)) and specify true for the reverseLayout param.

**Comment by veeresh1456** [comment]
i have changed in main_activity

from - >

    this.messagesAdapter = new MessagesListAdapter<Message>(this.senderId, null);
    this.messagesList.setAdapter(messagesAdapter);

to - >

    this.messagesAdapter = new MessagesListAdapter<Message>(this.senderId, null);
    this.messagesList.setAdapter(messagesAdapter, true);

But still problem persists. 

Looks like ide automatically calling that setAdapter(Adapter adapter) 

But after generating apk also message list not visible.

**Comment by brandon-haugen** [comment]
@veeresh1456, so even after making the change to use the two-argument version of `setAdapter()` you are getting the same exception? Or are you saying that you still have other issues?

In the code you shared, it does not look like you are loading any messages into `messagesAdapter` so that might be part of why you are not seeing the list.

The other part might be the layout that you are using for main_activity. I can't see the whole layout in the screenshot. It looks like you have most of the same settings though as the Sample for ChatKit does except you are using a Constraint layout where the Sample is using a Relative layout so there might be a few more constraints that you need to specify in your layout (or do not use a Constraint layout).

**Comment by veeresh1456** [comment]
Yes, the problem with constraint layout.
I have changed to relative layout. 
Now layout is looking good. 

Now, While adding message to adapter throws error. (May be code issue i will check)

Thanks for help.
