### ISSUE TITLE
Message with author name

### ISSUE THREAD

**Issue by akhilbv1** [stfalcon-studio/ChatKit#160]
Hello Guys, I am trying to build custom layout for incoming text messages and i think i can only change the position or behaviour of default view objects,but how to add the another view object i.e for example i need the author name to be displayed for incoming text messages.So How to actually do it? And is there a way to do it.

**Comment by brandon-haugen** [comment]
Yes, it is possible. Check out the documentation [here](https://github.com/stfalcon-studio/ChatKit/blob/master/docs/COMPONENT_MESSAGES_LIST.md#create-your-own-layout) where it describes how to create your own layout for the messages that are being displayed. There are also a number of attributes that you can use to change how the default layout looks if you do not want to create your own layout.

**Comment by akhilbv1** [comment]
"But what if you need not only to change the appearance of the elements, but also to change their position? It does not matter, because you can create your own layout! The only condition — IDs must match with default IDs, and widget types should not cause a ClassCastException (ie, either be the same or the subclass type)." 
This states that i need to use the same id's so is it possible to create new viewobjects with the existing one's because if i create a new view object than the id's will not match because that view object does not exists in library.
Or does that mean if i want to create a new ones than i can but if i want to edit or change the current ones than i need to use the id of view object which is mentioned in the library.
Just shed me some light as to which one is correct.

**Comment by brandon-haugen** [comment]
If you want to create a custom view, you just need to use the same IDs as the ones used in the library, which are

```java
@id/bubble (ViewGroup)
@id/messageText (TextView)
@id/messageTime (TextView)
@id/messageUserAvatar (ImageView)
```

Since the IDs are specific per layout, there is no problem with reusing the IDs.

You also have to provide the layout being used to ChatKit so that it knows what layout you are using. Here is the snippet from the project I work on that is using ChatKit

```kotlin
val holdersConfig = MessageHolders()
                .setOutcomingTextConfig(
                        OutgoingTextMessageViewHolder::class.java,
                        R.layout.outgoing_text_message_layout)

messagesAdapter = MessagesListAdapter(Author(phoneNumberForSender.orEmpty(), "").id, holdersConfig,null)
```

and here is the layout I have just for outgoing messages (the only customization we made was to add a field to display an email address under the outgoing message bubble)

```xml
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_marginBottom="8dp"
    android:layout_marginLeft="16dp"
    android:layout_marginRight="16dp"
    android:layout_marginTop="8dp">

    <com.google.android.flexbox.FlexboxLayout
        android:id="@id/bubble"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentEnd="true"
        android:layout_alignParentRight="true"
        android:layout_marginLeft="@dimen/message_outcoming_bubble_margin_left"
        android:layout_marginStart="@dimen/message_outcoming_bubble_margin_left"
        app:alignContent="stretch"
        app:alignItems="stretch"
        app:flexWrap="wrap"
        app:justifyContent="flex_end">

        <TextView
            android:id="@id/messageText"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignWithParentIfMissing="true"/>

        <TextView
            android:id="@id/messageTime"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_below="@id/messageText"
            android:layout_marginLeft="8dp"
            android:layout_marginStart="8dp"
            app:layout_alignSelf="center"
            app:layout_order="1"/>

    </com.google.android.flexbox.FlexboxLayout>

    <TextView
        android:id="@+id/messageAuthorEmail"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignRight="@id/bubble"
        android:layout_alignEnd="@id/bubble"
        android:layout_below="@id/bubble"/>

</RelativeLayout>
```

Hopefully that helps you @akhilbv1!

**Comment by ITWhiz4U** [comment]
Thanks so much.
This is very helpful for me.
best regards.

**Comment by akhilbv1** [comment]
Thank you for your quick reply.i am working on it.Thanks

**Comment by amitted** [comment]
@ITWhiz4U  are you able to do it??
