### ISSUE TITLE
AppCompat compatibility - version 27.1.1

### ISSUE THREAD

**Issue by AtlantisElsass** [stfalcon-studio/ChatKit#162]
Hey,

After looking so many hours for this problems, i'm asking your help...

I'm trying to build the project but i always get the 

"error: duplicate value for resource 'attr/inputTextSize' with config " ."
"error: resource previously defined here."

I tried to compile with differents version, and like advised in : "[Issue ChatKit](https://github.com/stfalcon-studio/ChatKit/issues/156)"

```
    ext.support_version = '27.1.1'

    implementation "com.android.support:support-v4:$support_version"
    implementation "com.android.support:design:$support_version"
    implementation "com.android.support:support-vector-drawable:$support_version"
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'
    implementation "com.android.support:gridlayout-v7:$support_version"
    implementation "com.android.support:recyclerview-v7:$support_version"
```

Thank you for your help...

**Comment by bevzaanton** [comment]
We have updated support_version to 27.1.1 in ChatKit version 0.2.3
