### ISSUE TITLE
Show name of sender

### ISSUE THREAD

**Issue by adamvar** [stfalcon-studio/ChatKit#166]
Is there a way to show the name of the sender with it's image?
thanks

**Comment by bevzaanton** [comment]
Hi @adamvar . You have to create your own layout and ViewHolder. After that you will be able to show any data what you want. [How to do it](https://github.com/stfalcon-studio/ChatKit/blob/master/docs/COMPONENT_MESSAGES_LIST.md#create-your-own-layout)

**Comment by amitted** [comment]
@bevzaanton please give us the solution I am not able to show the username can you help us to make it possible
