### ISSUE TITLE
MessageListAdapter: Exception thrown with some delete() methods called with unknown message ids

### ISSUE THREAD

**Issue by Qheb** [stfalcon-studio/ChatKit#169]
Hello,

Trying to delete messages that aren't into the list displayed by the `MessageListAdapter` can throw an Exception. This depends of which of the "delete" method provided by the `MessageListAdapter` is used:

- `delete(List<MESSAGE>)`, `deleteByIds(String[])`: Those methods called respectively with non-existent `MESSAGE`s or message ids throw a `java.lang.ArrayIndexOutOfBoundsException`.

- `delete(MESSAGE)` and `deleteById(String)`: Those methods called respectively with non-existent `MESSAGE` or message id just do nothing. The index value returned by `getMessagePositionById()` is indeed checked before being used.

[Here is the source of the said methods](https://github.com/stfalcon-studio/ChatKit/blob/master/chatkit/src/main/java/com/stfalcon/chatkit/messages/MessagesListAdapter.java#L227)

**Comment by bevzaanton** [comment]
Hi @Qheb ! Yeah, you are right! It will be fixed in ChatKit version 0.3.2
