### ISSUE TITLE
Shadow does not appear when CardView is displayed in MessageList

### ISSUE THREAD

**Issue by oboenikui** [stfalcon-studio/ChatKit#170]
When I register custom view (e.g. containing CardView) to MessageHolders, custom view have no shadow.

This happens because MessageList calls `setLayerType(View.LAYER_TYPE_SOFTWARE, null)`.
I can fix this problem with calling `messageList.setLayerType(View.LAYER_TYPE_HARDWARE, null)`, but is it the best solution?

(This may happen since https://github.com/stfalcon-studio/ChatKit/commit/95fc88e83c3119bc1466098d3069cb6c4059c65c )

**Comment by bevzaanton** [comment]
Hi @oboenikui ! Yes, now you can fix it by calling ```setLayerType(View.LAYER_TYPE_SOFTWARE, null)``` or setting ```android:layerType="hardware"``` . We will fix it in next ChatKit version.

**Comment by oboenikui** [comment]
Thanks!

**Comment by joostfunkekupper** [comment]
Hi @oboenikui, this issue has been address by #178. Just wanted to let you know :)
(Not sure when the next version will be released though - @bevzaanton)
