### ISSUE TITLE
Breaks with Android X :(

### ISSUE THREAD

**Issue by MTRNord** [stfalcon-studio/ChatKit#173]
Android X changed the namespaces of Components. After migrating this doesn't work anymore as the imports arent found :( Can we get a fix for this?

**Comment by mtangoo** [comment]
why not fix the names and make Pull Request? It should not be hard. 
IMHO, there is a need for new branch and new versioning for supporting of AndroidX (0.4??)

**Comment by Sagi363** [comment]
+1

**Comment by TinaT2** [comment]
@MTRNord You can add the androidx recyclerview library to solve the androidx related problem.
stackoverflow: Androidx project can't recognize the class of library using android.support.v7

**Comment by MTRNord** [comment]
@TinaT2 Don't mean to be rude but this issue was closed 2 years ago ^^
