### ISSUE TITLE
Version 0.3.0

### ISSUE THREAD

**Issue by gethunt** [stfalcon-studio/ChatKit#174]
Hi,
I'm using version 0.2.2

Today I've upgrade to version 0.3.0 
the scrolling is very not smooth, so I roll back to 0.2.2, 
just let you know so you can improve that
thanks

**Comment by aalap03** [comment]
I had same issue, Now I am reverting back to 0.2.2, Hope it will be resolved soon, thanks.

**Comment by marcinszulc** [comment]
Same issue here.

**Comment by bevzaanton** [comment]
#178
