### ISSUE TITLE
API 10 Support

### ISSUE THREAD

**Issue by ezefire** [stfalcon-studio/ChatKit#18]
Hi! Can you change the min sdk to API 10? I've seen they are not a lot of changes to do. It's simply to change the setBackground to ViewCompat.setBackground and two changes more.
Thanks

**Comment by drturing** [comment]
Please! 
Mine is 17, and need to import manually/ change the code. That way I lose out on your latest bug fixes
Thanks for sharing!!

**Comment by mradzinski** [comment]
@drturing ehhmm... I'm pretty sure the minSdk is set to 16... if you are pointing to 17 you should be more than able to use the gradle dependency. As of API 10, I don't really see how that would benefit anyone, the minimum SDK recommended by Google is (as the moment of writing this) 14.

**Comment by troy379** [comment]
Hello @drturing
There is no use for API 10 nowadays. As @mradzinski said, the current min version is 14 (moreover, Android Studio recommends us to use 16). For more info see [Android Dashboards](https://developer.android.com/about/dashboards/index.html).

Anyway, we've downgrade the minimal version to 14 in version `0.2.1`, but there is no plans for API 10.

Best regards, Alexander.
