### ISSUE TITLE
How can I do whatsapp like replies?

### ISSUE THREAD

**Issue by MTRNord** [stfalcon-studio/ChatKit#182]
Hi does anyone know what the easiest way is to do whatsapp like replies?

**Comment by mtangoo** [comment]
what does that mean?

**Comment by MTRNord** [comment]
@mtangoo 

![grafik](https://user-images.githubusercontent.com/1374914/44260139-d5368b00-a213-11e8-8151-6d80ec8ad28b.png)


I mean this kind of reply style

**Comment by mtangoo** [comment]
You mean quoting text?

**Comment by mtangoo** [comment]
I don't know how to do it exactly, but I believe you can do it with custom view holder for displaying. Am not sure what you can do for Text-editing.
There was similar issue with Signal. I don't use signal and so I cannot say much. You can download their app and test, if you find that one working, then go dig into their code to see how they did it.

All in all, yours is a common feature and would benefit everyone if you, after solving the problem, share the solution.

The issue am referring to is this one (though ending wasn't that happy):
https://github.com/signalapp/Signal-Android/issues/6017

**Comment by MTRNord** [comment]
@mtangoo I will take a look there thanks 👍

**Comment by mtangoo** [comment]
You are welcome!

**Comment by mtangoo** [comment]
BTW this might be of your interest: 
https://github.com/sharish/WhatsappFormatter
https://github.com/egimaben/WhatsappCloneAndroid
https://github.com/Shahar2k5/whatsappClone

I have not checked any of them in practice, so am not sure if they'll add any value!

**Comment by MTRNord** [comment]
Signal seems to do quotes with [this](https://github.com/signalapp/Signal-Android/blob/f9adb4e4554a44fd65b77320e34bf4bccf7924ce/src/org/thoughtcrime/securesms/components/QuoteView.java) and some other msg type specific functions. (See: https://github.com/signalapp/Signal-Android/search?p=2&q=quote&unscoped_q=quote ) So seems like I can start from their code. As soon as I have some working code I will tell it in here.

**Comment by mtangoo** [comment]
did you manage to find a solution?

**Comment by MTRNord** [comment]
@mtangoo I did not yet have time to work on this. So not yet.

**Comment by mtangoo** [comment]
Oh, OK!

**Comment by fukemy** [comment]
hi, did someone manage it to one library?

**Comment by mtangoo** [comment]
Nothing on the library. You can add your own VH with custom layout. Or you can modify sources and send PR
