### ISSUE TITLE
[FEATURE REQUEST] Pass image size if available to the imageLoader

### ISSUE THREAD

**Issue by MTRNord** [stfalcon-studio/ChatKit#183]
Hi it would be awesome if the imageLoader can be extended to pass also the image size to it if it is available. This can used in combination with Glide to pre occupy the space it requires in the timeline which can prevent accidential jumps while scrolling because of image that did not yet load.

Means in practice to pass height and width of an image to the imageLoader where I can tell Glide "hey the image you are loading is propably 10x10. Please put a placeholder in there for me."

**Comment by alexkrolinfinum** [comment]
Hi @MTRNord 
Good catch! I believe we would add this feature in the next release as well

**Comment by troy379** [comment]
Hi @MTRNord
Good catch! I believe we would add this feature in the next release as well

**Comment by bevzaanton** [comment]
Hi @MTRNord ! I implemented quick solution for this. Now in your custom image ViewHolder, what extends `MessageHolders.OutcomingImageMessageViewHolder` or `MessageHolders.IncomingImageMessageViewHolder`, you can override method `getPayloadForImageLoader(Message message)` where you can return your custom data.
You can check example [here](https://github.com/stfalcon-studio/ChatKit/blob/master/sample/src/main/java/com/stfalcon/chatkit/sample/features/demo/custom/holder/holders/messages/CustomOutcomingImageMessageViewHolder.java#L26).

**Comment by MTRNord** [comment]
Thanks I think this should be enough to close the Issue.
