### ISSUE TITLE
Public/protected access to items from MessagesListAdapter

### ISSUE THREAD

**Issue by 16arm** [stfalcon-studio/ChatKit#188]
Hi,

First, thank you for your library. Very nice work ! :)
I need to access to items from MessagesListAdapter in order to implement Glide RecyclerView Preloader and optimize medias loading.
Is there any problem about that ? Or do you have a best practice for that case ?

Thanks !

**Comment by bevzaanton** [comment]
Hi @16arm ! I will do `items` field in `MessagesListAdapter` and `DialogsListAdapter` in next release.

**Comment by lshannak** [comment]
Is there any update on this or a suggested work around?
I am trying to implement a message sent/delivered indicator and will need to access the messages by ID to be able to update the label to reflect the delivery report for the message.
