### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [stfalcon-studio/ChatKit#192]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by troy379** [comment]
Hi @jaldesign93!
Sounds good! Let us know when you'll have some mockups to show 😉

**Comment by mansya** [comment]
I have design logo for this project. what do you think ? do you like it ? which one do you like ? If there is a change. please let me know.
![chatkit](https://user-images.githubusercontent.com/33461607/44869530-0a34ea00-acb8-11e8-9956-14472e307dcf.png)

**Comment by mansya** [comment]
how about the logo. I really hope for a positive response from you.

**Comment by mansya** [comment]
hi sir. how about the continuation of this logo? do you like it ?
