### ISSUE TITLE
Support GIF Loading

### ISSUE THREAD

**Issue by JuVictor** [stfalcon-studio/ChatKit#197]
How to loading GIF?

**Comment by bevzaanton** [comment]
Glide has ability to load GIFs. So you can use it in [ImageLoader](https://github.com/stfalcon-studio/ChatKit/blob/master/docs/IMAGE_LOADER.md)
Maybe this [link](https://stackoverflow.com/questions/31082330/show-gif-file-with-glide-image-loading-and-caching-library) will be useful for you.
