### ISSUE TITLE
[BUG] In DialogListAdapter, addItem(dialog) adds the item to end of the list but updates the first item

### ISSUE THREAD

**Issue by mayuroks** [stfalcon-studio/ChatKit#198]
On adding a new dialog, item gets added but UI isn't updated.

```java
/**
     * Add dialog to the end of dialogs list
     *
     * @param dialog dialog item
     */
    public void addItem(DIALOG dialog) {
        items.add(dialog);
        notifyItemInserted(0);        <=== should be notifyItemInserted(items.length() - 1)
    }
```

**Comment by bevzaanton** [comment]
Hi! Yeah you are right! I can't understand how we missed it. I'll fix it. You can use method ```addItem(int position, DIALOG dialog)``` while I haven't update library.

**Comment by mayuroks** [comment]
Yup! I am using the `addItem(int position, DIALOG dialog)` for now.
