### ISSUE TITLE
Retry failed messages - doesn't moves to bottom

### ISSUE THREAD

**Issue by PrimozPernat** [stfalcon-studio/ChatKit#201]
Hi, we are using this lib for our chat purposes. But we have one problem with it. If the user sends a message and the sending fails we have a retry functionality. It changes the view from retry to send but the item stays at the same place.
We use the “uspert” method and in a loop just push all the items to the adapter.  The item changes but it stay in the same position. The desired behaviour would be to animate the item to the bottom.

**Comment by bevzaanton** [comment]
Hi Primoz! I think the best solution will be adding new method upsert(moveToStartIfUpdate). So we will not break the logic of application what are using upsert() method in the previous version of ChatKit. If you can please make PR.

**Comment by PrimozPernat** [comment]
@bevzaanton I have created a PR if you cloud take a look and submit the changes if everything looks OK.

**Comment by bevzaanton** [comment]
#209
