### ISSUE TITLE
Group chat username on each message

### ISSUE THREAD

**Issue by HassanRaza1112** [stfalcon-studio/ChatKit#203]
Hello I am trying to display username on each message bubble at top like wh
![sample](https://user-images.githubusercontent.com/19223147/46129708-f8138080-c250-11e8-89d7-e16d547caa85.JPG)
atsapp group chat !
How can i achieve that as i found nothing to do like this 
please guide me :)

**Comment by bevzaanton** [comment]
Duplicate #166
