### ISSUE TITLE
Get Message Position?

### ISSUE THREAD

**Issue by MTRNord** [stfalcon-studio/ChatKit#211]
Hi,
I would like to check if I currently have the newest message in view (means I am at the bottom) to be able in that case to scroll to new messages. If I am not at the bottom I dont want to scroll to new messages. 

Is there a way to check where the User currently is?

**Comment by bevzaanton** [comment]
Maybe I don't understand your problem clearly but I think you can use `listView.getFirstVisiblePosition()` to solve it.

**Comment by MTRNord** [comment]
@bevzaanton while that function sounds like it is perfect it doesn't seem like I can access it directly outside of the Adapter by default. I see it listet inside the Android docs but not using the IDE on the MessagesList type or the MessagesListAdapter type.

**Comment by MTRNord** [comment]
I do see it in this Android Doc: https://developer.android.com/reference/android/widget/AdapterView#getFirstVisiblePosition()

**Comment by bevzaanton** [comment]
MessagesList extends RecyclerView so you might do it in another way. Try this code
 `((LinearLayoutManager)messagesList.getLayoutManager()).findFirstVisibleItemPosition()`. Or you can use one of those methods:
```
int findFirstVisibleItemPosition();
int findFirstCompletelyVisibleItemPosition();
int findLastVisibleItemPosition();
int findLastCompletelyVisibleItemPosition();
```

**Comment by MTRNord** [comment]
One last question about it: Is the bottom item in the list 0 or the length of the array? (Ps: the above works)

**Comment by MTRNord** [comment]
Got it. Thanks for the help @bevzaanton  !

**Comment by kendovivi** [comment]
hi, 
I found that getFirstVisiblePosition() include the date header, that does not match the message item.
any solution?
