### ISSUE TITLE
when i load old msgs the the list is showed twice 

### ISSUE THREAD

**Issue by moanes1** [stfalcon-studio/ChatKit#213]
h tried to load old msgs from api the msgs is showed twice with the date and everything and the method is only called once 
` 
      if (msg_data.getString("sender_id").equals(senderId)) {

                                    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-mm-dd hh:mm:ss");
                                    Date convertedDate = new Date();
                                    try {
                                        convertedDate = dateFormat.parse(msg_data.getString("created_at"));
                                    } catch (ParseException e) {
                                        // TODO Auto-generated catch block
                                        e.printStackTrace();
                                    }
                                    System.out.println(convertedDate);
                                    Message message = new Message(senderId, msg_data.getString("msg"), convertedDate, sender);
                                    adapter.addToStart(message,false);
                                    messages.add(message);
                                } else {
                                    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-mm-dd hh:mm:ss");
                                    Date convertedDate = new Date();
                                    try {
                                        convertedDate = dateFormat.parse(msg_data.getString("created_at"));
                                    } catch (ParseException e) {
                                        // TODO Auto-generated catch block
                                        e.printStackTrace();
                                    }
                                    System.out.println(convertedDate);
                                    Message message = new Message(rereceiver_id, msg_data.getString("msg"), convertedDate, receiver);
                                    adapter.addToStart(message,false);

                                    messages.add(message);

                                }

                            }
                            adapter.addToEnd(messages,true);
`

**Comment by bevzaanton** [comment]
According to your code, you are adding the same message to adapter twice.
