### ISSUE TITLE
How to integrate chatkit with firebase?

### ISSUE THREAD

**Issue by omurbekjk** [stfalcon-studio/ChatKit#216]

**Comment by mtangoo** [comment]
https://github.com/stfalcon-studio/ChatKit/tree/master/docs

**Comment by omurbekjk** [comment]
@mtangoo It does not contain any info about backend integration

**Comment by mtangoo** [comment]
it shouldn't. Chatkit is a library that provides among other things a bunch of speciated RecyclerViews. So if you know RV then it works fine with any data source. 

It's your responsibility to fetch data as well as define data models that meets the adapter requirements.

So if you know Firebase already then you can just finish the rest

**Comment by andriizhumela** [comment]
Hi @omurbekjk ChatKit it's library for UI implementation with flexible possibilities for styling, customizing and data management with any data source. As @mtangoo said, It's your responsibility to fetch data.

**Comment by andriizhumela** [comment]
@omurbekjk If you still have some problem with this library, please reopen this issue again.
