### ISSUE TITLE
Avatar image for outgoing messages.

### ISSUE THREAD

**Issue by catalin-liviu** [stfalcon-studio/ChatKit#217]
Is it possible to add avatar image for outgoing image, maybe with custom layout?
Has anyone tried this?

**Comment by mtangoo** [comment]
It's possible. Check the documentation on adding custom layouts and viewholders

**Comment by andriizhumela** [comment]
Hi @catalin-liviu , @mtangoo's answer was correct. You can check [docs](https://github.com/stfalcon-studio/ChatKit/blob/master/docs/COMPONENT_MESSAGES_LIST.md#create-your-own-layout) or [example](https://github.com/stfalcon-studio/ChatKit/tree/master/sample/src/main/java/com/stfalcon/chatkit/sample/features/demo/custom/layout).

**Comment by andriizhumela** [comment]
@catalin-liviu If you still have some problem with this library, please reopen this issue again.
