### ISSUE TITLE
Is it possible to have more than 2 participants in a conversation?

### ISSUE THREAD

**Issue by asknask** [stfalcon-studio/ChatKit#218]
Does the MessageAdapter have support for more than 2 participants? It asks for one user ID to be able to differentiate between the sender/receiver. What if a third party is to be added to the conversation?

**Comment by mtangoo** [comment]
That will be a group chat,  isn't it?

**Comment by asknask** [comment]
> That will be a group chat, isn't it?

I suppose yes. I tried to find something regarding that in the documentation but couldn't,

**Comment by mtangoo** [comment]
https://github.com/stfalcon-studio/ChatKit/blob/master/docs/COMPONENT_DIALOGS_LIST.MD

**Comment by asknask** [comment]
> https://github.com/stfalcon-studio/ChatKit/blob/master/docs/COMPONENT_DIALOGS_LIST.MD

Sorry if this is stupid but.. that's a dialog list. I'm talking about what comes next when you click one of the dialogues. The message list (with more than 2 participants).

**Comment by mtangoo** [comment]
No question is stupid.
After clicking list you should have list of messages with different authors.

Those are messages you push via adapter.

Its something akin WhatsApp. Its MessageList.  Did I miss your question?

**Comment by asknask** [comment]
> No question is stupid.
> After clicking list you should have list of messages with different authors.
> 
> Those are messages you push via adapter.
> 
> Its something akin WhatsApp. Its MessageList. Did I miss your question?

This is the constructor for MessageList:

`MessagesListAdapter<Message> adapter = new MessagesListAdapter<>(senderId, imageLoader);`

My understand was that the ID you pass here becomes the senderId (my ID) and the other ID found in the message list will be the receiver. So if there are multiple receivers, will the library automatically be able to differentiate between them? (for instance, give their bubbles different colors?)

**Comment by mtangoo** [comment]
The best way is to look at that ID as yours so that the library can know hiw to layout messages (yours vs theirs). Now if you add messages from different authors the library will distinguish them based on author object associated with each message.

**Comment by asknask** [comment]
> The best way is to look at that ID as yours so that the library can know hiw to layout messages (yours vs theirs). Now if you add messages from different authors the library will distinguish them based on author object associated with each message.

Thanks a bunch.

**Comment by mtangoo** [comment]
You're always welcome

**Comment by mtangoo** [comment]
You can close the issue if your question is answered
