### ISSUE TITLE
Support for sdk below 28

### ISSUE THREAD

**Issue by vaishnavmhetre** [stfalcon-studio/ChatKit#222]
android.view.View$OnUnhandledKeyEventListener is not available below API-28
this issue shall be resolved as they throw a class not found exception and don't render dialog list

**Comment by KORuL** [comment]
ChatKit available on API >= 19

**Comment by andriizhumela** [comment]
Hi. @KORuL was right, ChatKit available from 19 API. Did you have any problem with ChatKit in your project?

**Comment by andriizhumela** [comment]
@vaishnavmhetre If you still have some problem with this library, please reopen this issue again.
