### ISSUE TITLE
Is there anyway to add typing view to the message list?

### ISSUE THREAD

**Issue by Raghuramchowdary** [stfalcon-studio/ChatKit#223]
I am trying to add typing view to the list, is there any easy way that I am missing here?

**Comment by mtangoo** [comment]
https://github.com/stfalcon-studio/ChatKit/pull/47

**Comment by Raghuramchowdary** [comment]
but that commit doesn't add ability to add to the `MessageList`

**Comment by mtangoo** [comment]
Yes. Message list does not deal with user typing, does it?

**Comment by Raghuramchowdary** [comment]
Yes it doesn't but what I meant is something similar to Facebook messenger.
Where someone types in and list shows that someone typing

**Comment by mtangoo** [comment]
Can you attach an image that shows what you are after?

**Comment by Raghuramchowdary** [comment]
Please have a look at attached

**Comment by mtangoo** [comment]
I can't see any attachment. Can you upload again

**Comment by Raghuramchowdary** [comment]
https://ibb.co/eQj35A

**Comment by Raghuramchowdary** [comment]
The three dots next to person indicates they are typing something

**Comment by mtangoo** [comment]
I don't know much about how to do it but one suggestion will be creating a
new kind of message with the dots that will be deleted once user stops
typing.

Just a quick thought

**Comment by andriizhumela** [comment]
ChatKit hasn't default view for displaying typing, but you can add [Typing Listener](https://github.com/stfalcon-studio/ChatKit/blob/master/docs/COMPONENT_MESSAGE_INPUT.MD#typing-listener) to Message Input and show your own view
