### ISSUE TITLE
Is there a way to customize MessageInput?

### ISSUE THREAD

**Issue by mechdon** [stfalcon-studio/ChatKit#224]
I'd like to know whether there is a way to add additional buttons to MessageInput.

**Comment by mtangoo** [comment]
I have just written my own!

**Comment by mechdon** [comment]
Thanks, am doing so too.

**Comment by shawntai** [comment]
May I ask if you ended up doing it? And if so how? Thanks!

**Comment by mechdon** [comment]
Shawn, you can modify the MessagesList xml file to include a layout (below the bottom layout) for the buttons and set its visibility to gone. Then set it to visible when the (+) add attachment button is pressed.

**Comment by shawntai** [comment]
@mechdon Thank you so much for your prompt reply! Wasn't expecting any response given how old this thread is to be frank. Thanks again for your help
