### ISSUE TITLE
changing a cell from bind,only change last cell

### ISSUE THREAD

**Issue by Azinnilchi** [stfalcon-studio/ChatKit#230]
hi, I'm developing a chat with your library. I have some different custom views, one of them is voice message which it has a play button and wave . I put my codes to `onBind` method in custom views like the example provided in library.
i've set a clicklistener in which changes the image in the cell, and after playing it I want to changed imageview again! but changing the imageview after playing only changes the imageview of last cell.
what am I doing wrong? is this a bug from this library?
this is some of my code bellow:
`@Override`
   ` public void onBind(Message message) {`
       ` super.onBind(message);`
        `play.setOnClickListener(v -> {`
            ` mediaPlayer.start();`
             `play.setBackgroundResource(R.drawable.ic_pause);`
       ` }`
        `mediaPlayer.setOnCompletionListener(mp -> {`
           ` play.setBackgroundResource(R.drawable.ic_play_white);`
           ` mediaPlayer.stop();`
        `});`
  `}`

**Comment by bevzaanton** [comment]
Hi @Azinnilchi . It's not a bug in the library. It's a default behavior of RecyclerView. 
What is `play` in your code? Where do you initialize it?
Can you provide full code of viewholder?

**Comment by Azinnilchi** [comment]
> Hi @Azinnilchi . It's not a bug in the library. It's a default behavior of RecyclerView.
> What is `play` in your code? Where do you initialize it?
> Can you provide full code of viewholder?

hi @bevzaanton ,there is a lot of things I've done in my viewholder,
play is a button, when the user click on it, my music must play, and change the button background to "pause". when playing is over, my button background must change to "play" again.
 note that `MyMediaplayer` is a singleton for playing music. 
`public class OutcomingVoiceMessageViewHolder
        extends MessageHolders.OutcomingTextMessageViewHolder<Message> {`
    `private Button play;`
     `MyMediaPlayer mediaPlayer;`
   ` public OutcomingVoiceMessageViewHolder(View itemView, Object payload) {`
        `super(itemView, payload);`
       ` play = itemView.findViewById(R.id.playOutComeBtn);`
    `}`
    `@Override`
    `public void onBind(Message message) {`
        `super.onBind(message);`
         `mediaPlayer = MyMediaPlayer.getInstance();`
          `play.setOnClickListener(v -> {`
           `mediaPlayer.start();`
            `play.setBackgroundResource(R.drawable.ic_pause);`
            `}`
             `mediaPlayer.setOnCompletionListener(mp -> {`
               `play.setBackgroundResource(R.drawable.ic_play_white);`
               `mediaPlayer.stop();`
              `});`
     `}`
`}`
I hope the code above is not confusing. thank you

**Comment by bevzaanton** [comment]
You reset mediaPlayer OnCompletionListener for every list item. That's why it's working only for the last item.

**Comment by Azinnilchi** [comment]
> You reset mediaPlayer OnCompletionListener for every list item. That's why it's working only for the last item.

I don't understand. so where should I put OnCompletionListener so that background of play btn of the cell I want change?!
