### ISSUE TITLE
Support only one avatar in the last messages in group sequence messages from same user.

### ISSUE THREAD

**Issue by antranvn** [stfalcon-studio/ChatKit#231]
Support only one avatar in the last messages in group sequence messages from same user.
We can see this feature in most of chat application out there. Could you give me some information how to support it?

**Comment by mario** [comment]
I did this. I just check if the last 4 or 5 messages are same author and if they are, hide avatar.

**Comment by antranvn** [comment]
Thank @mario, where do you check it? In the DemoMessagesActivity?

**Comment by fukemy** [comment]
@antranvn did u solved this? Thanks

**Comment by antranvn** [comment]
> @antranvn did u solved this? Thanks

Hello, I didn't solve it 😂

**Comment by fukemy** [comment]
i solved this, just clone my fork then import as library, although it's not good solution

**Comment by antranvn** [comment]
Thanks @fukemy

**Comment by Hatzen** [comment]
I dont think this issue should be resolved, as the PR is still outstanding:  https://github.com/stfalcon-studio/ChatKit/pull/271  
Forking is not a good long term solution..
