### ISSUE TITLE
Is there a public release of this library that has been migrated to AndroidX?

### ISSUE THREAD

**Issue by kgoodrick** [stfalcon-studio/ChatKit#233]
I am trying to migrate my project across to AndroidX, and have run into a conflict between RecyclerView implementations.  This is due to the 0.3.3 release still using "com.android.support:appcompat-v7:27.1.1".  

I understand that MTRNord has a fork of this project that has been migrated at https://github.com/Nordgedanken/ChatKit, but there is no release artifact?

Just wondering if there is a public release version of this library that has been migrated to AndroidX?

**Comment by MTRNord** [comment]
I did use jitpack in my Fork. But my fork is heavily modified anyway and not getting any updates anymore (as I switched to epoxy by airbnb which is a lot quicker and more stable for recycler views)

**Comment by kgoodrick** [comment]
Thanks for the heads up Marcel.

**Comment by knaeckeKami** [comment]
My fork is now on Android X: https://github.com/knaeckeKami/ChatKit
Thanks to @vyasenenko how opened the pull request.

My fork contains only minimal, non-breaking changes (making the adapter more open to inheritance, i.e. changing some methods/inner classes from default/private visibility to public/protected.

**Comment by andriizhumela** [comment]
AndroidX is not a big problem. You just have to enable "enableJetifier" propperty.
More details are given in the [documentation](https://github.com/stfalcon-studio/ChatKit#androidx)

**Comment by TinaT2** [comment]
You can add the androidx recyclerview library to solve the androidx related problem.
[stackoverflow: Androidx project can't recognize the class of library using android.support.v7](https://stackoverflow.com/questions/62846856/androidx-project-cant-recognize-the-class-of-library-using-android-support-v7/62850348#62850348)
