### ISSUE TITLE
Failed to resolve: com.google.android:flexbox:1.0.0

### ISSUE THREAD

**Issue by HJaliliani** [stfalcon-studio/ChatKit#234]
my project is based on Androidx and when i add chatkit library in gradle sync will failed and got this error!

but when i clone your repo that is not on androidx it working!
any solution?

**Comment by JavaCafe01** [comment]
I'm getting this error even when I manually import the module...

**Comment by JavaCafe01** [comment]
OK I figured it out, add 
` maven { url  "https://google.bintray.com/flexbox-layout" }` 
to repositories in the project level gradle file.

**Comment by mismaiti** [comment]
i add @JavaCafe01  suggestion and still experience the same issue..

**Comment by HJaliliani** [comment]
Thanks to @JavaCafe01 .
I solved to problem by adding  maven { url "https://google.bintray.com/flexbox-layout" } in Build.gardle ( Project file), but must add it at both of repositories section to get a successful build.
I Put the complete gradle  build file code:
`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext.kotlin_version = '1.2.71'
    ext.roomVersion = '1.1.1'
    ext.roomRxVersion = '1.1.1'
    ext.navVersion = "1.0.0-alpha07"


    repositories {
        google()
        jcenter()

        mavenCentral()
        mavenLocal()
        maven { url "https://jitpack.io" }
        maven { url "https://maven.google.com" }
        maven {
            url 'https://maven.fabric.io/public'
        }
        **maven { url "https://google.bintray.com/flexbox-layout" }**

    }
    
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'io.fabric.tools:gradle:1.27.0'
        classpath 'com.google.gms:google-services:4.1.0'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()
        mavenLocal()
        maven { url "https://jitpack.io" }
        maven { url "https://maven.google.com" }
        **maven { url "https://google.bintray.com/flexbox-layout" }**
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`

**Comment by mismaiti** [comment]
i did put in both repositories and still, and then i upgrade to Jdk8 and it sync succesfully
