### ISSUE TITLE
Messages Dont't Show Until Scroll 

### ISSUE THREAD

**Issue by aminosman** [stfalcon-studio/ChatKit#238]
I am having an issue where my messages are not showing until I scroll a bit. I have followed the docs to the letter, so not sure what is going on here.

I call `adapter.addToEnd(Arrays.asList(messages), true);` (I have also tried the other message adding methods with the same issue ) from the main thread (which seems to be the leading cause of the RecycleView not updating until some UI interaction).

My layout template is identical to the app sample (RelativeLayout -> MessageList -> View (bar) -> MessageInput) with no modifications from the one in this project.

I do want to add a side note (I dont think this is part if the issue but just incase) I am using Greenrobots `EventBus` like this `@Subscribe(threadMode = ThreadMode.MAIN)` to add new messages as they come in.

**Comment by amin-mirmahmoudi** [comment]
can you explain how to  solve scroll issue ?

**Comment by amin-mirmahmoudi** [comment]
below code solve my problem :)
``messagesList.getLayoutManager().scrollToPosition(adapter.getItemCount() - 1);``
