### ISSUE TITLE
Change some interface method's name

### ISSUE THREAD

**Issue by gab07** [stfalcon-studio/ChatKit#24]
Hi, I'm using Kotlin in my project and in some models, the overrided method clash with the default getter (or setter) defined by Kotlin. Like this: 

`    var lastMessage: ChatMessage? = null
    
    override fun getLastMessage(): ChatMessage? {
        return lastMessage
    }
    override fun setLastMessage(message: ChatMessage?) {
        lastMessage = message
    }`

This give me an error at compile time. 

So I'm suggesting to rename interfaces method's name to something like "getDialogId" in order to avoid that clash with common field's names.

**Comment by mradzinski** [comment]
In Kotlin you should make use of data classes and not simple classes. When you use a data class, you must declare as private the fields declared in the constructor.

```kotlin
data class Conversation(private val id: String,
                            private val name: String,
                            private val users: List<IUser>,
                            private val count: Int,
                            private var lastMessage: MeshMessage?): IDialog<Message> {

    override fun getId(): String = this.id
    override fun getUnreadCount(): Int = this.count
    override fun getDialogName(): String = this.name
    ...
}
```

**Comment by troy379** [comment]
Hi @gab07 !
Did @mradzinski's answer help you?

**Comment by gab07** [comment]
@troy379 Yeah!!  
@mradzinski I didn't know about data classes, thanks!

**Comment by rdias002** [comment]
It'd be great if just like the getters we could have public setters available. I say this because I am using this with Firebase and Firebase requires public setters. Making these member variables private prevents Firestore's toObject() method from accomplishing it's task. Without the public setters we'd have to explicitly create setters and Android Studio at current doesn't auto-generate them in Kotlin.
Thank you✌✌

**Comment by fukemy** [comment]
hi, can anyone help me implement adapter with kotlin, thanks
![Screen Shot 2020-12-04 at 18 24 28](https://user-images.githubusercontent.com/8202437/101158194-f2e6c300-365d-11eb-818b-770c61496983.png)
