### ISSUE TITLE
detect scroll up and down

### ISSUE THREAD

**Issue by Azinnilchi** [stfalcon-studio/ChatKit#247]
hi, I used `onLoadMore` for scrolling down and detect top of the chat for load previous messages, is there anyway to detect the bottom of chat and do something on scrolling up ?!

**Comment by thanhnguyenduc157** [comment]
Has anyone found a solution?
I need detect bottom of chat and when scroll up, please help

**Comment by andriizhumela** [comment]
Hi @Azinnilchi, No by default you can use only `onLoadMore` callback and thats all. You can create you own ListAdapter, extended from MessagesListAdapter and implement this feature.

**Comment by andriizhumela** [comment]
@Azinnilchi, did my answer help you?
