### ISSUE TITLE
Need Feature : Message State (Sending, Sent, Delivered and Read)

### ISSUE THREAD

**Issue by christlin** [stfalcon-studio/ChatKit#25]
This is a nice library, But missing the message state feature. If you add the message states such as sending, sent, delivered and read it will be awesome.

**Comment by troy379** [comment]
Hello @Aseyth !
To add this feature you need to create (or inherit existing) view holder. Nevertheless, we already did something similar in sample. Check the [sample](https://github.com/stfalcon-studio/ChatKit/blob/master/sample/src/main/java/com/stfalcon/chatkit/sample/features/demo/custom/holder/holders/messages/CustomOutcomingTextMessageViewHolder.java) and [documentation](https://github.com/stfalcon-studio/ChatKit/blob/master/docs/COMPONENT_MESSAGES_LIST.md#not-enough-features-create-your-own-holder) to see how it's done.

Best regards, Alexander
