### ISSUE TITLE
How to add local image?

### ISSUE THREAD

**Issue by nicemak** [stfalcon-studio/ChatKit#252]
Hi,

i want to add local image and voice message with duration?
any working and easy example?

**Comment by KORuL** [comment]
See example. It implemented

**Comment by andriizhumela** [comment]
@nicemak you should check this [sample](https://github.com/stfalcon-studio/ChatKit/tree/master/sample/src/main/java/com/stfalcon/chatkit/sample/features/demo/custom/media)

**Comment by andriizhumela** [comment]
@nicemak Was my answer helpful? If you have questions or problems with the library, please re-open this issue.
