### ISSUE TITLE
Select device's local photo or take picture with camera in MessageInput default button

### ISSUE THREAD

**Issue by udongeex** [stfalcon-studio/ChatKit#255]
Hello, I'm new to android and come across your awesome libs :D 
Just like the title said, is there a way to implement it ? Really appreciate if you could give me some sample code.

**Comment by issamux** [comment]
@udongeex 
The bad news is, this Library isn't designed to be extensible for that ... 
The good news is, the easiest way i  found, was extending MessageInput class and add Ui element needed and my own listeners, ... i ll push a merge request if i have time to make this lib more generic and extensible.

**Comment by udongeex** [comment]
Thanks :D

**Comment by andriizhumela** [comment]
Hi @udongeex this feature is not a part of library. You can implement this with any file picker or third party library. Just add ```input.setAttachmentsListener``` and override ```onAddAttachments```

**Comment by andriizhumela** [comment]
@udongeex Was the previous answer helpful? Do you have any questions about library?
