### ISSUE TITLE
image corners not rounded wtih glide

### ISSUE THREAD

**Issue by winkleak** [stfalcon-studio/ChatKit#257]
at first launch chat screen image corners work normal, but if move to next screen and back to chat, then RoundedImageView corners is not rounded with glide but it work with picasso

**Comment by andriizhumela** [comment]
Hi @winkleak could you send a sample of your code?

**Comment by winkleak** [comment]
> Hi @winkleak could you send a sample of your code?

i notice, if make some changes in RoundedImageView class, then all works fine

`  private fun applyScaleToRadii(m: Matrix) {
            val values = FloatArray(9)
            m.getValues(values)
            // added this checking
            if (values[0] != 0f) {
                for (i in mRadii.indices) {
                    mRadii[i] = mRadii[i] / values[0]
                }
             // moved from method draw()
                mBoundsConfigured = true
            }
        }`

**Comment by winkleak** [comment]
Андрей, я прошу прощения что на русском, у меня плохо с английским, увидел
что вы закрыли issue, считаете нет смысла править? Суть проблемы в том что
при использовании glide в качестве image лоадера, при возврате к фрагменту
с чатом из следующего в стэке фрагмента закругление углов image view
пропадает. В моем коде ничего особенного не было все из сэмплов.

пн, 8 июл. 2019 г., 16:37 Andrii Zhumela <notifications@github.com>:
