### ISSUE TITLE
scrollToPosition() is not working

### ISSUE THREAD

**Issue by debuggerUA** [stfalcon-studio/ChatKit#258]
Hello!
I've encountered a problem and can't resolve it myself.
I'm using ChatKit for chat functionality in my app, and I need to add scroll-to-top functionality.
But calling DialogsList.scrollToPosition(0) is doing nothing.
smoothScrollToPosition(), scrollToPositionWithOffset() doesn't work also.

`<com.stfalcon.chatkit.dialogs.DialogsList
            android:id="@+id/chats_list"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_below="@id/chats_requests_container"
            app:dialogUnreadBubbleBackgroundColor="@color/colorAccent"
            app:dialogAvatarHeight="40dp"
            app:dialogAvatarWidth="40dp"
            app:dialogDateColor="@color/dlg_date"
            app:dialogMessageTextColor="@color/dlg_date"
            app:dialogMessageTextSize="14sp"
            app:dialogDateSize="14sp"
            app:dialogUnreadDateColor="@color/dlg_date"
            app:dialogDividerLeftPadding="0dp"/>`

**Comment by MrTheGood** [comment]
As a workaround for the issue, just add `implementation "androidx.recyclerview:recyclerview:1.0.0"` to your build.gradle and it'll be fine.

At least this worked for me.

**Comment by andriizhumela** [comment]
Hi @debuggerUA. @MrTheGood 's answer helped you?

**Comment by debuggerUA** [comment]
@andriizhumela I didn't tried it, the feature request was cancelled.
Sorry I missed the @MrTheGood 's answer.
