### ISSUE TITLE
Text Not displaying for the first message in the send textinput for Android version Pi 

### ISSUE THREAD

**Issue by DhirajG** [stfalcon-studio/ChatKit#260]
For the First time when we initiate the chat the text message does not appear if we click send it does send the text. If we minimize the keyboard we can see the text...

**Comment by andriizhumela** [comment]
@DhirajG Could you send a sample of you code?

**Comment by andriizhumela** [comment]
@DhirajG Was this problem resolved?
If not, please re-open this issue again.
