### ISSUE TITLE
Androidx

### ISSUE THREAD

**Issue by Moh-Droid** [stfalcon-studio/ChatKit#261]
hii, how can i use this library in project use androidX?

**Comment by knaeckeKami** [comment]
you can use my fork, which is on androidx: https://github.com/knaeckeKami/ChatKit

**Comment by alexnivanov** [comment]
@knaeckeKami thx so much for this!

**Comment by andriizhumela** [comment]
AndroidX is not a big problem. You just have to enable enableJetifier.
More details are given in the [documentation](https://github.com/stfalcon-studio/ChatKit#androidx)

**Comment by TinaT2** [comment]
@mohodroid  You can add the androidx recyclerview library to solve the androidx related problem.
[stackoverflow: Androidx project can't recognize the class of library using android.support.v7](https://stackoverflow.com/questions/62846856/androidx-project-cant-recognize-the-class-of-library-using-android-support-v7)
