### ISSUE TITLE
Load More View to (footer of Dialog List ,Header of Message List)

### ISSUE THREAD

**Issue by habahbehbassam** [stfalcon-studio/ChatKit#264]
Is Chatkit Support Loading View for pagination ?

**Comment by andriizhumela** [comment]
Hi @habahbehbassam No, it isn't supported. Chatkit has callback onLoadMode and you can implement your own view for displaying loading state.

**Comment by andriizhumela** [comment]
@habahbehbassam do you have any questions about library?

**Comment by habahbehbassam** [comment]
@andriizhumela  yes please , 
1. How to display image with text in same message 
2. How to customize Input view 
3. com.stfalcon.chatkit.utils.RoundedImageView Not support GIF  
4. How to customize Message Adapter to set mItems from list to observableList 

thanks,

**Comment by andriizhumela** [comment]
1) You must implement you own [layout](https://github.com/stfalcon-studio/ChatKit/blob/master/docs/COMPONENT_MESSAGES_LIST.md#create-your-own-layout)
2) [Make it look the way you want](https://github.com/stfalcon-studio/ChatKit/blob/master/docs/COMPONENT_MESSAGE_INPUT.MD#make-it-look-the-way-you-want)
3) You can [create your own holder](https://github.com/stfalcon-studio/ChatKit/blob/master/docs/COMPONENT_MESSAGES_LIST.md#not-enough-features-create-your-own-holder) and use another component for displaying GIF
4) You can clean data
```
viewModel.get().messages.observe(this, Observer { 
   it?.let { messages ->
      if (messageAdapter == null) {
         messageAdapter =
            MessagesListAdapter(viewModel.get().currentUser.id, ImageLoader { imageView, url, _ ->
                Glide.with(this).load(url).into(imageView)
            })
            conversationMessagesList.setAdapter(messageAdapter)
         }
         messageAdapter?.clear()
         messageAdapter?.addToEnd(messages, true)
      }
  })
```

**Comment by habahbehbassam** [comment]
@andriizhumela thanks for answers ,But for last answer i need to set observableList without make observe and set to end on every change, please show this [example ](https://github.com/radzio/android-data-binding-recyclerview/blob/master/recyclerview-binding/src/main/java/net/droidlabs/mvvm/recyclerview/adapter/BindingRecyclerViewAdapter.java) .

Thanks,

**Comment by andriizhumela** [comment]
No, you can't set observableList to default messageAdapter. If you use databinding, you have to create own adapter but we have no sample for this case.

**Comment by habahbehbassam** [comment]
@andriizhumela Thanks man
