### ISSUE TITLE
How can i change message time format?

### ISSUE THREAD

**Issue by BhargavVGhodasara** [stfalcon-studio/ChatKit#265]
How can i changes message time format?please help me.
@stfalcon

**Comment by andriizhumela** [comment]
Hi @BhargavVGhodasara you should check [documentation](https://github.com/stfalcon-studio/ChatKit/blob/master/docs/COMPONENT_MESSAGES_LIST.md#dates-format-for-headers)

For example you can implement ```DateFormatter.Formatter``` to your Fragment or Activity with chat and override method format

```
override fun format(date: Date): String {
        return when {
            DateFormatter.isToday(date) -> getString(R.string.chat_date_header_today)
            DateFormatter.isYesterday(date) -> getString(R.string.chat_date_header_yesterday)
            else -> DateFormatter.format(date, "EEEE, dd MMMM")
        }
    }
```
```
messagesAdapter.setDateHeadersFormatter(this)
```

**Comment by dennishylau** [comment]
I think OP was asking about the **message** time format (the one below each message bubble), not the header one. How can I change that?
