### ISSUE TITLE
How to update image message without reloading the image 

### ISSUE THREAD

**Issue by mechdon** [stfalcon-studio/ChatKit#266]
I am using the messagesAdapter.update(message) to update changes to my image message. However, I want to make changes only to the text while maintaining the same image, without having the image to be inflated in the message bubble again. Is this possible?

**Comment by andriizhumela** [comment]
Hi @mechdon when you called ```messagesAdapter.update(message)``` the whole message will update.

**Comment by mechdon** [comment]
Thanks
