### ISSUE TITLE
"Admin Messages"

### ISSUE THREAD

**Issue by Aseyth** [stfalcon-studio/ChatKit#27]
Thanks for this awesome library.
I wanted to know if there is a way to add a special "conversation bubble" to show an "admin message" like "UserA has joined the channel" ?

**Comment by troy379** [comment]
Hello @Aseyth !
You can achieve this just adding your custom content type. The only thing you need is to create you own layout and view holder for it. See [the documentation](https://github.com/stfalcon-studio/ChatKit/blob/master/docs/COMPONENT_MESSAGES_LIST.md#custom-content-types) to see how it's done

Best regards, Alexander
