### ISSUE TITLE
Chat Layout

### ISSUE THREAD

**Issue by uaeuae** [stfalcon-studio/ChatKit#28]
Currently when I use the library, the chat appears starts from bottom to top. Could anyone help me in re configuring the chat layout to start from top to bottom like whatsapp?

**Comment by mradzinski** [comment]
How about reversing your messages array? AFAIK the messages layout doesn't apply any sorting to the messages it receives, thus you should be totally able to reverse your messages array to make it look the way you want.

**Comment by uaeuae** [comment]
Thank you for your replay mradzinski. I think you understood the question wrong. What I meant, currently, the bubbles starts from down (bottom of the screen). What I want the other way around. I want to bubbles to start from top screen like the below screen as the following screenshot. 
![chat](https://cloud.githubusercontent.com/assets/16542046/25628761/731f1a68-2f78-11e7-8d6b-788f0ea1fb0c.PNG)

**Comment by mradzinski** [comment]
You are not gonna be able to do it, not without forking your own copy of this repo and changing [this line](https://github.com/stfalcon-studio/ChatKit/blob/master/chatkit/src/main/java/com/stfalcon/chatkit/messages/MessagesList.java#L69). LinearLayoutManager has the following constructor: ```LinearLayoutManager(Context context, int orientation, boolean reverseLayout)```, stfalcon-studio chose to pass ```true``` to the _reverseLayout_ parameter and it'll stay true unless you manually modify their code.

**Comment by mradzinski** [comment]
I made a PR to close this issue. You can check the solution here: #31

**Comment by troy379** [comment]
Thanks for your replies @mradzinski !
Unlike your solution, I've added overloading for `setAdapter` method in `DialogsList` and `MessagesList`, with which you can set reverse mode to `false` (due to versioning).
Please, update library version to `0.2.1`

Best regards, Alexander.

**Comment by shubhral** [comment]
I was facing the same issue since yesterday where the dialogs in my dialogList were appearing from bottom. Thanks to this issue raised by @uaeuae , I finally got it working the desired way by overriding default reverse mode to `false`.
I think it'd be great if you add this in your documentation as well @troy379 

Cheers! :)

**Comment by CallumCoombes** [comment]
Is there a way to do this that doesn't also reverse the date rows?

**Comment by ptrudec** [comment]
@troy379 In adapter reverseLayout = True and when adding messages to list with addToEnd reverse = True. Is there any option when there isn't enough messages to fill the screen that messages doesn't have padding from top?
![Screen Shot 2019-05-02 at 11 00 24](https://user-images.githubusercontent.com/7883306/57065383-878e7f80-6cc9-11e9-810b-3541467d6a26.png)
