### ISSUE TITLE
New message always added to the top with addToStart and addToEnd

### ISSUE THREAD

**Issue by hamamd-et** [stfalcon-studio/ChatKit#282]
I have been struggling with this issue for the last 2 days. No matter what function i use addToStart or addToEnd, my new message is always added to the top.

```
       messagesAdapter.addToEnd(
            listOf(
                MessageWrapper(message)
            ),
            false
        )

        messagesAdapter.addToStart(MessageWrapper(message), true)
```

I tried both true and false with the addToEnd but still no change. I am doing this in kotlin.  MessageWrapper is the class implementing the IMessage interface.

Can any one please help in this regard.

**Comment by hamamd-et** [comment]
It was logically error on my end. Its working fine :)

Great lib, thanks

**Comment by bipinvaylu** [comment]
> It was logically error on my end. Its working fine :)
> 
> Great lib, thanks

Hey @hamamd-et I am facing same issue, Can you please let me know what was your logic error?  I might figure out mine one. Thanks.

**Comment by bipinvaylu** [comment]
@hamamd-et After inspective their code and document, I believe I am following their integration document properly. So i created new issue here, Can you please provide your feedback on this: https://github.com/stfalcon-studio/ChatKit/issues/352
