### ISSUE TITLE
get View of dialog List item 

### ISSUE THREAD

**Issue by mubtadasyed** [stfalcon-studio/ChatKit#29]
Hi, I want to show popup menu when a user longClick on any dialog list item, to show popup menu I need the view of that list item, how can I get that? kindly help.

**Comment by mradzinski** [comment]
```DialogsList.setOnDialogLongClickListener()``` should give you a Dialog instance of the dialog the user is pressing. So, having that instance you should invoke ```DialogList.getLayoutManager()``` to get the ```LinearLayoutManager``` instance held by the _RecyclerView_ that _DialogsList_ extends from. Once you have the reference to that _LayoutManager_ it's easy, you should invoke ```LayoutManager.findViewByPosition``` which will return the view you are looking for.

**Comment by mubtadasyed** [comment]
How can I get the position of that dialog instance, as dialog adapter does not have that method? kindly help!

**Comment by mradzinski** [comment]
_DialogsListAdapter_ doesn't seem to provide a getter for the list of items you need, so you either keep track of your actions (by having a secondary list of DIALOG synchronized with the one held inside the _DialogsListAdapter_) or fork this repo and add a ```getItems()``` method on the _DialogsListAdapter_ class. If you obtain that list of dialogs then you'll be able to call ```List.indexOf```.

**Comment by mubtadasyed** [comment]
Thanks, it worked!

**Comment by mradzinski** [comment]
I already created a PR to allow the users to retrieve the current position of a certain dialog. As soon as it gets merged (if it is) you can get back to relay on the official implementation of this library.

**Comment by troy379** [comment]
Hi @mubtadasyed !
Starting from version `0.2.1` you can use `OnMessageViewClickListener` and `OnMessageViewLongClickListener`, which has the same behavior as previous listeners, but also returns view. Hope it helps you.

Best regards, Alexander.

**Comment by mradzinski** [comment]
Hey @troy379, the main reason for creating the PR is because providing listeners can be very limiting for the developer. For example, how does the developer implement a swipe to delete functionality based on those listeners? IMHO, having the possibility to retrieve the view itself (through RecyclerView and RecyclerView.Adapter methods) is much more flexible than providing a listener itself.

**Comment by bevzaanton** [comment]
#32 merged. Thanks @mradzinski
