### ISSUE TITLE
MessageList empty when screen turns off/ app goes to the background.

### ISSUE THREAD

**Issue by iWillBeUnderYourBed** [stfalcon-studio/ChatKit#299]
Whenever the screen is not on the app, like turning the screen off, or the app goes to the background, the MessagesList is empty / blank, the messages just disappear. 
Rest of the activity is still there, activity can be recreated (backbutton and then click on the chat again). 
Turning the screen (Landscape <-> Portrait) is save, the messages stay.

**Comment by Andrew-Chen-Wang** [comment]
Any updates on this @iWillBeUnderYourBed I've just started taking a look at this repository and this seems like a pretty weird issue.

Can you list the simulator and target SDK? Are you using AndroidX? Etc. (I'm also new to the huge updates for Android, but the more the better so I may help out).

**Comment by iWillBeUnderYourBed** [comment]
Closing issue, since I made a mistake, that wasn't the librarys fault:
I populated the MessagesList in onStart and when onStart was called a second time (aka the screen reappeared) I messed up the data to populate the MessagesList with. 
Moved the code to onCreate, now it runs fine.
