### ISSUE TITLE
How to disable scrolling when selecting a message?

### ISSUE THREAD

**Issue by RUSSCITY** [stfalcon-studio/ChatKit#316]
Whenever a message is selected/deselected the view does some automatically scrolling. See video:

![20200428_165537](https://user-images.githubusercontent.com/9445518/80503305-f7cdf080-8971-11ea-8265-6a5ea9eb9b39.gif)

I would like to disable it. Thanks for your help.
Awesome library btw!

**Comment by dekanako** [comment]
see this issue
https://github.com/stfalcon-studio/ChatKit/issues/308
whenever ive updated a message i saw this scrolling to ive fixed it by removing the constraint layout and add a relative layout like in the sample app

**Comment by RUSSCITY** [comment]
Thank you, I had to simply "wrap" MessagesList into RelativeLayout, than it works in a ConstraintLayout as well. 

This issue can be closed.

**Comment by fukemy** [comment]
pls do not use ConstraintLayout because of laggy
