### ISSUE TITLE
Update demo app in Playstore 

### ISSUE THREAD

**Issue by mtangoo** [stfalcon-studio/ChatKit#319]
App in Playstore was updated in 2017. Currently it does not show avatars. It's great demo and need not to be abandoned. 

Thank you for this great library and the demo.

**Comment by tangible-idea** [comment]
I agree. Even with the sample project, it does not showing avatars. How can I make it?

**Comment by mtangoo** [comment]
We decided to fork it and update it with my opinionated stuffs (Like Swipe gestures). 
You can test it here: https://github.com/hosannahighertech/MessageKit

It is as of now 100% compatible with ChatKit though we expect BC breaking changes soon!

**Comment by fukemy** [comment]
@mtangoo  hi buddy, did u solved "hiding avatar for same user"

**Comment by mtangoo** [comment]
>@mtangoo hi buddy, did u solved "hiding avatar for same user"

No. But you can open an issue in the fork so that when I get time I can try to put that
https://github.com/hosannahighertech/MessageKit
