### ISSUE TITLE
Layout is not adjusting when keyboard is shown

### ISSUE THREAD

**Issue by arnis71** [stfalcon-studio/ChatKit#34]
I am implementing the same layout as shown in example which looks like this:
```
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.stfalcon.chatkit.messages.MessagesList
        android:id="@+id/messages_list"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:dateHeaderTextColor="#ffffff"
        android:overScrollMode="never"
        app:textAutoLink="all"
        android:layout_above="@+id/input"
        android:visibility="invisible"/>

    <View
        android:layout_width="match_parent"
        android:layout_height="1dp"
        android:layout_above="@+id/input"
        android:layout_marginLeft="16dp"
        android:layout_marginRight="16dp"
        android:background="#9e9e9e"/>

    <com.stfalcon.chatkit.messages.MessageInput
        android:id="@+id/input"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        app:inputHint="enter a message..." />

</RelativeLayout>
```
But for some reason the input layout is not lifting up when keyboard is shown. Maybe because it is fragment inside the viewpager and not separate activity? And how can i fix it?

**Comment by mradzinski** [comment]
When the soft keyboard appears on the screen, the amount of space available for the application's UI reduces. The system makes decisions on how to organize the available space between the application's UI and soft keyboard in the following way:

- If the window content contains a ListView, RecyclerView or a ScrollView, the application's window is resized provided all the content is visible.
- If resizing is not feasible, `pan` and `scan` approach is used, which simply involves scrolling the application's window so that the currently focused view is visible.

I'm assuming that the parent (container) of your fragment is a `FrameLayout`, right? Regardless of this, would you mind trying the following and check if it works?

```Java
public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
  getDialog().getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_PAN | WindowManager.LayoutParams.SOFT_INPUT_STATE_HIDDEN);
}
```

**Comment by demmydwi** [comment]
i tought you just missed to put theme on AndroidManifest.xml
like this
`<activity
            android:name=".features.demo.def.DefaultDialogsActivity"
            android:theme="@style/BlueTheme" />`

**Comment by mradzinski** [comment]
Hey @demmydwi, Have you tried doing exactly that but using a regular EditText? You'll notice it behaves the same way as with ChatKit. That is more of a system issue than a Library one. 

Like I previously stated, [this piece of code](https://github.com/mikepenz/MaterialDrawer/blob/aa9136fb4f5b3a80460fe5f47213985026d20c88/library/src/main/java/com/mikepenz/materialdrawer/util/KeyboardUtil.java) written by Mike Penz will help you overcome the system limitation.

**Comment by demmydwi** [comment]
looks like your solution is better
thanks @mradzinski

**Comment by troy379** [comment]
I hope the issue has solved.

Thank you once again for help, @mradzinski 
We appreciate this!

**Comment by Anil0319** [comment]
Hi, there is still issue when you trying and activity to be scrolled when keyboard..and its full screen from style file..

Please help

**Comment by MSI-Shamim** [comment]
to adjust, just make the component: 
isScrollContainer="true";
That's it. Now when the keyboard will appear the layout will automatically adjust its blank spaces. 
Happy Coding!

**Comment by benardelia** [comment]
> When the soft keyboard appears on the screen, the amount of space available for the application's UI reduces. The system makes decisions on how to organize the available space between the application's UI and soft keyboard in the following way:
> 
> * If the window content contains a ListView, a RecyclerView or a ScrollView, the application's window is resized provided all the content is visible.
> * If resizing is not feasible, `pan` and `scan` approach is used, which simply involves scrolling the application's window so that the currently focused view is visible.
> 
> I'm assuming that the parent (container) of your fragment is a `FrameLayout`, right? Regardless of this, would you mind trying the following and check if it works?
> 
> ```java
> public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
>   getDialog().getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_PAN | WindowManager.LayoutParams.SOFT_INPUT_STATE_HIDDEN);
> }
> ```
> 
> If this doesn't work, [this piece of code](https://github.com/mikepenz/MaterialDrawer/blob/aa9136fb4f5b3a80460fe5f47213985026d20c88/library/src/main/java/com/mikepenz/materialdrawer/util/KeyboardUtil.java) by Mike Penz might help too. Use it during `onCreateView` like: `new KeyboardUtil(this, findViewById(R.id.fragment_container));`

it's more than 7 years but the answer is really helpful
