### ISSUE TITLE
Textwatcher for MessageInput

### ISSUE THREAD

**Issue by Aseyth** [stfalcon-studio/ChatKit#35]
Hello, is there a way to implement a textwatcher for the MessageInput, I need to know when I'm typing and when I'm done typing. Thank you.

**Comment by mradzinski** [comment]
`MessageInput.getInputEditText()` returns an `EditText` so you can just append a custom `TextWatcher` through the `EditText.addTextChangedListener(TextWatcher)` method.

**Comment by Aseyth** [comment]
This is exactly what i needed thanks !
