### ISSUE TITLE
Getting a caption with an image message?

### ISSUE THREAD

**Issue by shusain93** [stfalcon-studio/ChatKit#36]
Is there any good way (other than I suppose detecting images with captions and then duplicating the message? It'd look better if I could have the text be a part of the same bubble. It's not really that super edgecase so I figured it's worth suggesting here instead of just making a custom holder

**Comment by troy379** [comment]
Hi!
Yes, it's a really good idea to implement such kind of logic. I suppose that the next version will handle this case as well. And thank you for sharing your vision!

Best regards
