### ISSUE TITLE
Doubt about chat groups.

### ISSUE THREAD

**Issue by JesusValera** [stfalcon-studio/ChatKit#37]
Hello, I'm implementing the library but I've noticed that when you create a dialogList, you've to set how many users will be on that chat.
I want to create a anonymous chat, something like Telegram groups where  anyone can register into the application (via firebase) and there will be cardviews with content and a button where any one can press and join to a chat with the topic of this card.
Is this possible? What I've supposed to put when I create a dialogList into User[] argument.

PS: I save into firebase database a object called 'AppUser' with some attributes like 'name', 'picture' and 'password'. I know that it's not secure and firebase implements it's own login implementation.

Thank you so much. :)

**Comment by mradzinski** [comment]
The users field on`IDialog` is currently only used for adding the user avatar next to their latest message if the dialog is a group chat (this happens, if my memory doesn't fail me, on the`DialogsListAdapter` class). As per it's implementation, you can perfectly pass it an empty list.

```java
ivLastMessageUser.setVisibility(dialogStyle.isDialogMessageAvatarEnabled() &&
    dialog.getUsers().size() > 1 ? VISIBLE : GONE);
```

**Comment by JesusValera** [comment]
Thank you so much! Thats right.
