### ISSUE TITLE
IMessage implementation getUser() method has confict with FirebaseDatabase in the Runtime! 

### ISSUE THREAD

**Issue by MarkVyper** [stfalcon-studio/ChatKit#38]
How to fix this?

**Comment by mradzinski** [comment]
I'm assuming you are implementing a POJO which you use for Firebase AND for ChatKit, hence the model implements IUser. As a rule of thumb: **Never implement interfaces on domain models unless you have full control over them.** You should actually separate that model in two, one for Firebase (`FirebaseMessage.java` for example) and one for ChatKit (`MyCoolAppMessage.java`), being the latest the one implementing `IMessage`. The reason behind this is that your Firebase implementation might change during time, but ChaKit hardly will (or vice versa).

**Comment by MarkVyper** [comment]
Thank you! But now I have other problem. When I send message it duplicates and I see double message. When I go to the Firebase Console I see that there is only one message which i sent but in the chat I see several.

**Comment by MarkVyper** [comment]
@mradzinski  Thank you very much!
