### ISSUE TITLE
Dismiss keyboard on enter

### ISSUE THREAD

**Issue by JordanOsterberg** [stfalcon-studio/ChatKit#4]
There is no way I can dismiss the keyboard when the user presses enter. A method such as getEditText() from within MessageInput would allow this feature to be possible.

Edit: It would also be great if the keyboard could be dismissed when the area above it is touched, like Instagram or other DM/IM/Messaging clients.

**Comment by Sekhmet** [comment]
I added such method (`getMessageInput`) in #2 but it wasn't merged yet.

**Comment by troy379** [comment]
Hello @JordanOsterberg !
I don't know why you need to hide a keyboard every time a user presses "submit" (I'm not sure it would be convenient for user), but you can achieve this with `InputListener.onSubmit` method.
Anyway, in version `0.1.2` we've added getters for EditText, so you can do now anything you need. Or even extend the view and do your stuff using protected fields.
