### ISSUE TITLE
Typing indicator

### ISSUE THREAD

**Issue by jonisak** [stfalcon-studio/ChatKit#40]
Hi 
Is there any support for a typing indicator?

Best regards
Jonas

**Comment by toanpv** [comment]
You can check [this pull request](https://github.com/stfalcon-studio/ChatKit/pull/47)

**Comment by ChrisLMills** [comment]
@toanpv 
Has this pull request been accepted?

**Comment by ChrisLMills** [comment]
This would be greatly appreciated.

**Comment by bevzaanton** [comment]
#47 merged

**Comment by fukemy** [comment]
any ideal for typing indicator, not listener?
