### ISSUE TITLE
Support for adding multiple button in MessageInput for Attachment,Emoticon,Camera 

### ISSUE THREAD

**Issue by ynagarjuna1995** [stfalcon-studio/ChatKit#43]
Is there a way to override the existing behaviour of `MessageInput` so that I can keep multiple button like WhatsApp ?

I will be able to make pull request if you guys give rough idea on how to do it 😃

**Comment by mradzinski** [comment]
There's no in-built support for such functionality, but`MessageInput` extends from `RelativeLayout`, so it's just a matter of adding those buttons and playing around with some `LayoutProperties`.

**Comment by troy379** [comment]
@ynagarjuna1995 IMHO, for this case it's much simpler to create your own view with all of the buttons included.

Best regards, Alex
