### ISSUE TITLE
Selection mode for Dialog list

### ISSUE THREAD

**Issue by inromualdo** [stfalcon-studio/ChatKit#44]
Hi. This library save my like. Thank you so much.

Why not implement selection mode (MessageList) to DialogList too.

**Comment by bevzaanton** [comment]
Hi, @inromualdo ! 
When we were starting to develop ChatKit, we made research about the expediency of implementing selection mode in DialogList. Most applications(like Telegram, Viber, Messager) don't have selection mode in DialogList for a number of reasons. So we also abandoned it.
