### ISSUE TITLE
Have DialogsListAdapter implement android.widget.Filterable?

### ISSUE THREAD

**Issue by ebernie** [stfalcon-studio/ChatKit#49]
It would be nice to be able to filter dialog title or user. Ideally allow the library user to pass their own Filter objects to be used for filtering?

**Comment by ulaserdegor** [comment]
up

**Comment by bevzaanton** [comment]
Unfortunately, ChatKit does not provide such functionality. We have plans to add this functionality in the future but If you have some ideas will be great if you do it and create pull request.
