### ISSUE TITLE
Error while importing library

### ISSUE THREAD

**Issue by judemanutd** [stfalcon-studio/ChatKit#5]
`Error:org.gradle.api.UncheckedIOException: Could not HEAD 'https://jitpack.io/com/github/stfalcon/chatkit/0.1.2/chatkit-0.1.2.pom'. Received status code 401 from server: Unauthorized`
`Error:org.gradle.api.resources.ResourceException: Could not get resource 'https://jitpack.io/com/github/stfalcon/chatkit/0.1.2/chatkit-0.1.2.pom'.`

I keep getting this error when trying to pull the library

**Comment by bevzaanton** [comment]
Hi @judemanutd !
I can't reproduce your problem. Do you use gradle dependency:
```
compile 'com.github.stfalcon:chatkit:0.1.2'
````
