### ISSUE TITLE
Support for READ messages and UNREAD messages

### ISSUE THREAD

**Issue by sacOO7** [stfalcon-studio/ChatKit#52]
Are there any plans for showing read and unread messages? Just let me know if this is possible via custom layouts

**Comment by bevzaanton** [comment]
Hi @sacOO7 !
Yes, it's possible via custom layouts and holders
https://github.com/stfalcon-studio/ChatKit/blob/master/docs/COMPONENT_MESSAGES_LIST.md#make-it-look-the-way-you-want

**Comment by ChrisLMills** [comment]
@bevzaanton 
Are there plans to include this as part of the library?

**Comment by pedrofsn** [comment]
@bevzaanton
Are there plans to include this as part of the library?
// 2

**Comment by Hayko985** [comment]
Yes this would be a great solution adding this messages state part in library. @sacOO7  If you have time, please add this feature))) Thank you.
