### ISSUE TITLE
Setting Dialog's unReadCount to 0 doesn't change the typeface of title and date from unread to default

### ISSUE THREAD

**Issue by shubhral** [stfalcon-studio/ChatKit#53]
I faced this issue today and have tried a couple of workarounds without any success.
**Issue -** 
Once the user clicks on a dialog in _dialogList_ screen having unreadCount > 0 and goes to the _messageList_ screen, and then presses back and comes back to the dialogList screen, I'm resetting that dialog's unreadCount to 0 in order to update the UI. And after doing that, the _unreadCountBubble_ hides, textColor of date & title changes to normal, but **what doesn't change is the typeface of title and date. It still remains bold**.

Here's how I'm using dialogList in my xml -
```
 <com.stfalcon.chatkit.dialogs.DialogsList
            android:id="@+id/dialogsList"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:dialogDateStyle="normal"
            app:dialogDividerLeftPadding="0dp"
            app:dialogMessageTextColor="@color/colorPrimaryLightGrey"
            app:dialogMessageTextSize="@dimen/text_view_size_medium"
            app:dialogTitleTextColor="@color/colorPrimary"
            app:dialogTitleTextSize="@dimen/text_view_size_large"
            app:dialogTitleTextStyle="normal"
            app:dialogUnreadBubbleBackgroundColor="@color/red"
            app:dialogUnreadBubbleTextSize="@dimen/text_view_size_very_small"
            app:dialogUnreadDateColor="@color/colorPrimary"
            app:dialogUnreadDateStyle="bold"
            app:dialogUnreadTitleTextColor="@color/colorPrimary"
            app:dialogUnreadTitleTextStyle="bold" />
```

And here's what I'm doing on returning to dialogList screen from messageList screen -
```
@Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (requestCode == MSG_LIST && resultCode == RESULT_OK && data != null) {
            Dialog updatedDialog = data.getParcelableExtra(DIALOG_OBJECT);
            dialogAdapter.updateItemById(updatedDialog);
       }
}
```

Can you tell me as to what am I doing wrong here, and how you'd have ideally updated the dialogList UI from unread to normal state for a particular dialog. 
It works fine if I set the items in adapter and reset the adapter again, but that's not the right solution.

Thanks in advance! Really appreciate your time and efforts working on this library.
Cheers!

**Comment by bevzaanton** [comment]
Hi, @shubhral !
I have fixed it. Please update ChatKit version to 0.2.2.
Thank you for interest in our library!
