### ISSUE TITLE
Set user avatar from Resources

### ISSUE THREAD

**Issue by adriamt** [stfalcon-studio/ChatKit#54]
Hi, I started to use this library and I'm no able to find how to do this.

I'm following the sample that you provide and change something to fit in how I want. The problem is that I want to show a default avatar image that I have in my drawable or mipmap folders, but the IUser class uses a String avatar.

Any clue how to achieve what I want? 

Thanks

**Comment by bevzaanton** [comment]
Hi, @adriamt ! Whan you init ImageLoader you can do something like that

```
ImageLoader imageLoader = new ImageLoader() {
            @Override
            public void loadImage(ImageView imageView, String url) {
                if (url != null) {
                    Picasso.with(MessagesListActivity.this).load(url).into(imageView);
                } else {
                    imageView.setImageResource(<default image resource id>);
                }
            }
        };
```

**Comment by adriamt** [comment]
I did something like that, I've checked if the image view id equals to R.id.messageUserAvatar and if it's true I set my drawable. But this only works with the chunk data tat you provided on FixtureData and MessagesFixtures, with the messages that I enter through the input or through adapter.addToStart() it shows an empty avatar, I didn't use the loader.

**Comment by adriamt** [comment]
@bevzaanton any clue of what I wrote in my last post?

**Comment by bevzaanton** [comment]
I don't quite understand you. Can you provide some code sample what exactly do you do?

**Comment by adriamt** [comment]
Sure, here you are @bevzaanton .

I've used your [DemoMessagesActivity](https://github.com/stfalcon-studio/ChatKit/blob/master/sample/src/main/java/com/stfalcon/chatkit/sample/features/demo/DemoMessagesActivity.java) and [StyledMessagesActivity](https://github.com/stfalcon-studio/ChatKit/blob/master/sample/src/main/java/com/stfalcon/chatkit/sample/features/demo/styled/StyledMessagesActivity.java) as starting point.

I've modified the ImageLoader as you suggested to this:
```
       imageLoader = new ImageLoader() {
            @Override
            public void loadImage(ImageView imageView, String url) {
                if(imageView.getId() == R.id.messageUserAvatar){
                    imageView.setImageResource(R.drawable.fonendoscopio);
                }else {
                    if (url != null) {
                        Picasso.with(imageView.getContext()).load(url).into(imageView);
                    } else {
                        imageView.setImageResource(R.drawable.fonendoscopio);
                    }
                }
            }
```
And I've modified the OnSubmit to this
```
@Override
    public boolean onSubmit(CharSequence input) {
       messagesAdapter.addToStart(new Message(Utils.getRandomId(), user, input.toString()), true);
        return true;
    }
```
Where user is this:
`user = new User("1", "User", null,true);`

And when I execute the App, all the messages generated by this code of above has the avatar modified, but the messages from the input don't have any avatar:
   ```
@Override
    public void onLoadMore(int page, int totalItemsCount) {
        if (totalItemsCount < TOTAL_MESSAGES_COUNT) {
            loadMessages();
        }
    }
    protected void loadMessages() {
        new Handler().postDelayed(new Runnable() { //imitation of internet connection
            @Override
            public void run() {
                ArrayList<Message> messages = MessagesFixtures.getMessages(lastLoadedDate);
                lastLoadedDate = messages.get(messages.size() - 1).getCreatedAt();
                messagesAdapter.addToEnd(messages, false);
            }
        }, 1000);
    }
```

**Comment by bevzaanton** [comment]
@adriamt What `sanderId` do you use for creating `MessagesListAdapter`? I can't understand, are you talking exactly about the avatar of outgoing message user?
Can you provide a screenshot?

**Comment by adriamt** [comment]
Oh, I've just realised that the only messages that have avatar are the ones that have the `userId `equal to `senderId`  and I think that it should be the normal operation. Is it the normal operation of this library? Only the sender can have an avatar or everybody on the `messagelist `can have ant avatar?.
But the problem is that the only messages that have avatar are the ones that are loaded with the `loadMessages` function that I included in my last post if I include more messages using this method ` messagesAdapter.addToStart(new Message(Utils.getRandomId(), sofiaBot, input.toString()), true);` where the user `sofiaBot` has the same id as the `senderID` of the Adapter, it happen this:
![medicsen_screenshot](https://user-images.githubusercontent.com/11394100/27527888-189c41a0-5a4e-11e7-8d73-3cef98b61f37.png)
As you can see, the first messages have an avatar but the last doesn't have.

**Comment by bevzaanton** [comment]
In default realization: only interlocutors can have an avatar. The sender doesn't have. 
Please, re-read this part of [documentation](https://github.com/stfalconstudio/ChatKit/blob/master/docs/COMPONENT_MESSAGES_LIST.md#set-an-adapter):

> If user doesn't have avatar image, you can return null, and image will not be shown in incoming message item

But you are creating user with avatar = null `user = new User("1", "User", null,true);`
So in your case, you should create user with avatar just with empty String.
`user = new User("1", "User", "", true);`

**Comment by adriamt** [comment]
I've tried putting avatar = "" and it still doesn't show the avatar.
I'll expose my situation to clarify what I want to do.

My idea is to make a chatbot, where the bot will be a user with id = 0 and the user who interacts with the bot will be a user with id = 1.
```
 sofiaBot = new User("0", "Sofia", "",true);
 user = new User("1", "User", "",true);
```
Now when the user types something and send it through onSubmit I use what I said before, and then the bot answer the user this form
```
messageToSend = new Message(getRandomId(),sofiaBot,botResponse);
messagesAdapter.addToStart(messageToSend, true);
```
I want to set a default avatar for the bot and the user from my resources, but the problem is what I said I'm not able to show the avatar but it shows if I maintain the part of loadmessages from the demo.

**Comment by bevzaanton** [comment]
Sorry, @adriamt I forgot one thing. If the avatar is an empty string then it will not show too. So try to pass some string when you create User. 
My advice is read these topics:
https://stackoverflow.com/questions/9296999/android-reference-resource-drawable-as-a-url/31217414
https://stackoverflow.com/questions/6602417/get-the-uri-of-an-image-stored-in-drawable
In those topics, you can find how to get drawable resource as Uri, what can be converted to String and then you can pass to User constructor.

**Comment by adriamt** [comment]
Finally!!
I tried first replacing the empty strings for non-empty strings and then I what you mentioned about uris. This is how it looks now.
This is my user:
```
 Uri sofiaAvatar = Uri.parse("android.resource://"+getApplicationContext().getPackageName()+"/"+R.drawable.fonendoscopio);
        sofiaBot = new User("0", "Sofia", sofiaAvatar.toString() ,true);
```
And now this is my loader:
```
imageLoader = new ImageLoader() {
            @Override
            public void loadImage(ImageView imageView, String url) {
                Picasso.with(imageView.getContext()).load(url).into(imageView);
            }
        };
```

Thank you very much for your help.
One last question. Is it possible to show the avatar from the sender?  Or you have in mind to implement it?
Thank you again ;)

**Comment by bevzaanton** [comment]
You can implement showing the avatar from the sender by yourself.  For it, you have to create your own layout and holder. Loot at this for more information: https://github.com/stfalcon-studio/ChatKit/blob/master/docs/COMPONENT_MESSAGES_LIST.md#create-your-own-layout

**Comment by yyuripp** [comment]
I found a solution to show avatar from resources without Picasso. 

`User sofia = new User("0", "Sofia", "mipmap/ic_launcher", true);`
or
`User sofia = new User("0", "Sofia", "drawable/avatar", true);`

`protected ImageLoader imageLoader = new ImageLoader() {
        @Override
        public void loadImage(ImageView imageView, String url) {
            int resID = getResources().getIdentifier(url , "drawable", getPackageName());
            imageView.setImageResource(resID);
        }
    };`

**Comment by vikalp0299** [comment]
Hi!!!, For  same code  the avatars are coming on my friend's phone(s7 edge) and not on mine (One plus 5t & S10 edge+)
Can you suggest why is this happening
