### ISSUE TITLE
How to listen the user avatar click event?

### ISSUE THREAD

**Issue by williambao** [stfalcon-studio/ChatKit#55]
Hi,
How to listen the user avatar tapped event?

If user avatar clicked, I want to open user profile image.
But When click image view or text view, need to open some menus.

**Comment by bevzaanton** [comment]
Hi, @williambao !
I just added this feature and updated library. 
You should update ChatKit to version 0.2.2.
After that, you can solve your problem using a method like this:
```
   super.messagesAdapter.registerViewClickListener(R.id.messageUserAvatar,
                new MessagesListAdapter.OnMessageViewClickListener<Message>() {
                    @Override
                    public void onMessageViewClick(View view, Message message) {
                        AppUtils.showToast(DefaultMessagesActivity.this,
                                message.getUser().getName() + " avatar click",
                                false);
                    }
                });
```

**Comment by williambao** [comment]
@bevzaanton ,

**Comment by williambao** [comment]
Hi @bevzaanton ,
Thanks,

But `OnMessageViewClick` methods seems always called whatever i click user avatar view or text content view.
I want to have 2 different action for avatar/content view click event.
<img width="594" alt="william_and_wechat__chats__and_how_to_listen_the_user_avatar_click_event__ _issue__55_ _stfalcon-studio_chatkit" src="https://user-images.githubusercontent.com/779521/27992290-577e29cc-64c3-11e7-9290-1a3e368f6fba.png">

**Comment by fukemy** [comment]
@williambao hi buddy, did u solved this, i having same problem
