### ISSUE TITLE
学习和主要点的笔记

### ISSUE THREAD

**Issue by molele2** [stfalcon-studio/ChatKit#58]
chatkit现在有很多了偶然的机会看到这个，虽不一定是最好的，但是对于我这种android开始的时候介入，最终放下4年以上时间来说的人，对于新的UI的模式还是挺累，感谢ChatKit的开发人员，有些重点的地方梳理如下：本来想提交到Wiki的，这个交给作者了，因为Wiki没办法打开

chatkit 中的消息被定义在RecyclerView中采用了MVP结构设计，Recyclerview中的事件，被外部接口包装并被set到RecyclerView具体可以在Activity来定义具体实现
参考
http://blog.csdn.net/chathello/article/details/69056663

chatkit中消息收发的信息的展示部分

收发信息的展示都在
MessageHolders代码里，
 this.incomingTextConfig = new HolderConfig<>(DefaultIncomingTextMessageViewHolder.class, R.layout.talk_receive_msg);
        this.outcomingTextConfig = new HolderConfig<>(DefaultOutcomingTextMessageViewHolder.class, R.layout.talk_send_msg);

收发信息颜色
   MessagesListStyle
   style.incomingTextLinkColor = typedArray.getColor(R.styleable.MessagesList_incomingTextLinkColor,
                style.getSystemAccentColor());
        style.outcomingTextLinkColor = typedArray.getColor(R.styleable.MessagesList_outcomingTextLinkColor,
                style.getSystemAccentColor());
收发信息显示的区别：

根据发送的senderId即该位是否和窗体的用户ID一致

进入点在类MessagesListAdapter中的
  public int getItemViewType(int position) {
        return holders.getViewType(items.get(position).item, senderId);
    }

调用
MessageHolders中的下面的

 int getViewType(Object item, String senderId) {
        boolean isOutcoming = false;
        int viewType;

        if (item instanceof IMessage) {
            IMessage message = (IMessage) item;
            isOutcoming = message.getUser().getId().contentEquals(senderId);
            viewType = getContentViewType(message);

        } else viewType = VIEW_TYPE_DATE_HEADER;

        return isOutcoming ? viewType * -1 : viewType;
    }

消息列表中数据的输入：
在每个activity中如下的地方initAdapter
super.dialogsAdapter.setItems(DialogsFixtures.getDialogs());  //输入数据

chatkit中消息列表里的代码在dialogsListAdapter中，xml文件是talk_item_dialog，其中未读消息的标签如下：
  <TextView
            android:id="@+id/dialogUnreadBubble"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignEnd="@+id/dialogAvatar"
            android:layout_alignRight="@+id/dialogAvatar"
            android:layout_alignTop="@+id/dialogAvatar"
            android:layout_marginEnd="-5dp"
            android:layout_marginRight="-5dp"
            android:layout_marginTop="-5dp"
            android:background="@drawable/bubble_circle"
            android:ellipsize="end"
            android:fontFamily="@string/font_fontFamily_medium"
            android:gravity="center"
            android:lines="1"/>

**Comment by bevzaanton** [comment]
Sorry man, I don't know Chinese.

**Comment by bzp2010** [comment]
@bevzaanton This is a guide for new users to avoid errors

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Xiaomi MI 5s Plus 发送_
