### ISSUE TITLE
Can't set input hint programmatically

### ISSUE THREAD

**Issue by mahi05** [stfalcon-studio/ChatKit#6]
Hello, there isnt any option for set hint by using java code. Please fix it

**Comment by bevzaanton** [comment]
Hi, @mahi05 ! Sorry for late response.
You can set input hint programmatically in CatKit version 0.1.2 . For example:
```java
MessageInput input = (MessageInput) findViewById(R.id.input);
input.getInputEditText().setHint("Your hint");
```
Thanks for interest in our library!
