### ISSUE TITLE
Manifest merger failed - `allowBackup` tag duplicated

### ISSUE THREAD

**Issue by lwasylkowski** [stfalcon-studio/ChatKit#60]
Seems like the library project's manifest includes `allowBackup` and `supportsRtl` application attributes. I don't think these are necessary, since it's application's role to define whether it supports RTL/backup. 

Right now the presence of these attributes is problematic, since if the consumer of the library explicitly sets `allowBackup=false` in their app's Manifest, the manifest merger complains about duplicate element, forcing the developer to use `<tools:replace="android:allowBackup">`

I'm happy to submit a pull request if what I say makes sense to you

**Comment by hbmartin** [comment]
Agreed - the <application> tag is auto-generated when creating new libraries in Android Studio, but I can't think of any reason why it needs to be here.
https://github.com/stfalcon-studio/ChatKit/pull/61
