### ISSUE TITLE
Gradle Install is not working

### ISSUE THREAD

**Issue by takawww** [stfalcon-studio/ChatKit#63]
Hi All

compile 'com.github.stfalcon:chatkit:0.2.2' is added

gradle return Error:(47, 13) Failed to resolve: com.github.stfalcon:chatkit:0.2.2

Please hrlp

Regards
Taka Wong

**Comment by guangzhun** [comment]
Great.
Thanks for your effort

**Comment by takawww** [comment]
Hi guys

did the issue get fixed?
I still not able to install thru gradle :(

Best Regards

**Comment by bevzaanton** [comment]
Hi, @takawww ! I can't reproduce this issue. Do you have this lines in your project gradle file?
```
repositories {
    jcenter()
}
```

**Comment by takawww** [comment]
@bevzaanton , ya, you rock

I can install now, sorry i made the stupid mistake.

**Comment by fanrunqi** [comment]
Could not resolve com.github.stfalcon:chatkit:0.2.2.

I have this in project gradle file,

`allprojects {
    repositories {
        jcenter()
        google()
    }
}`

Please help...

**Comment by bevzaanton** [comment]
Hi @fanrunqi ! Can you provide the code of your app gradle file?

**Comment by fanrunqi** [comment]
@bevzaanton  

thanks a lot, i fix it 

cause by my gradle setting is offline work,
