### ISSUE TITLE
How can I update the specific message?

### ISSUE THREAD

**Issue by TheOska** [stfalcon-studio/ChatKit#66]
Is it possible to update the specific message content (UI) while in runtime?

The case that I encounter is when user send the message when the app is disconnecting the internet, it will show the loading icon, which can be achieved in onBind() function in custom view holder. But the question is how can I update the specific message (hidden the loading icon) when reconnecting the network?

Thanks for your help!!

**Comment by evstep** [comment]
Yes, you can use MessagesListAdapter method   `update(MESSAGE
 message)`

**Comment by TheOska** [comment]
Sorry for late reply! it works perfectly !! Thanks
