### ISSUE TITLE
Put user name on top of the message

### ISSUE THREAD

**Issue by PedroBarbosaPT** [stfalcon-studio/ChatKit#7]
Can you help me creating the Layout of setIncoming where the username appears on top like messenger does? Like this: "Panmorn"

![chatkit help](https://cloud.githubusercontent.com/assets/13065435/23774974/47a82c0a-051e-11e7-903f-4d2760c85b31.PNG)

I tried to do but I was nowhere close
`
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_marginBottom="8dp"
    android:layout_marginLeft="16dp"
    android:layout_marginRight="16dp"
    android:layout_marginTop="8dp">

    <com.stfalcon.chatkit.utils.ShapeImageView
        android:id="@id/messageUserAvatar"
        android:layout_width="40dp"
        android:layout_height="40dp"
        android:layout_alignParentBottom="true"
        android:layout_marginRight="8dp" />

    
    <com.google.android.flexbox.FlexboxLayout
        android:id="@id/bubble"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginRight="@dimen/message_incoming_bubble_margin_right"
        android:layout_toRightOf="@id/messageUserAvatar"
        app:flexWrap="wrap"
        app:alignItems="stretch"
        app:alignContent="stretch"
        app:justifyContent="flex_end"
        android:orientation="vertical">

        <TextView
            android:id="@id/messageText"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content" />

        <TextView
            android:id="@id/messageTime"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            app:layout_alignSelf="center"
            android:layout_marginLeft="8dp"
            android:layout_below="@id/messageText"/>

    </com.google.android.flexbox.FlexboxLayout>

    <TextView
        android:id="@+id/nomeuser"
        android:layout_width="wrap_content"
        android:layout_alignTop="@id/bubble"
        android:text="Pedro Barbosa"
        android:layout_marginTop="10dp"
        android:layout_marginLeft="@dimen/message_incoming_bubble_margin_right"
        android:layout_height="wrap_content" />

</RelativeLayout>
`

**Comment by meetakshay99** [comment]
Were you able to achieve this? I also want to add username on top.

**Comment by meetakshay99** [comment]
I was able to achieve it with following for the image cell:

**Comment by troy379** [comment]
Hello @PedroBarbosaPT and @meetakshay99 !

If you want to change the appearance of messages, you need to create layouts for incoming and outcoming messages accordingly and register them in adapter. Check the [sample](https://github.com/stfalcon-studio/ChatKit/blob/master/sample/src/main/java/com/stfalcon/chatkit/sample/features/demo/custom/layout/CustomLayoutMessagesActivity.java) and [documentation](https://github.com/stfalcon-studio/ChatKit/blob/master/docs/COMPONENT_MESSAGES_LIST.md#create-your-own-layout) to see how it's done.

Best regards, Alexander
