### ISSUE TITLE
Guide

### ISSUE THREAD

**Issue by rlee1990** [stfalcon-studio/ChatKit#73]
Is there a guide that takes you step by step on how to use this? Whats on here is not well written.

**Comment by kirvis250** [comment]
Existing guide is sufficient. I suggest you to Learn how android RecyclerView works. :)

**Comment by rlee1990** [comment]
@kirvis250 I know how to use one the guide talks in bits I am making the suggestion for others that my my new to android it would allow for more people to use this.
