### ISSUE TITLE
How to create new ViewHolder from scratch

### ISSUE THREAD

**Issue by CallumCoombes** [stfalcon-studio/ChatKit#77]
I am trying to create a new view holder completely from scratch, as to avoid inheriting the `onBind()` in classes such as `OutcomingImageMessageViewHolder` etc.

So in an attempt to do this I have created a class from scratch, defined as:
```
public class ChatOutcomingImageMessageViewHolder <MESSAGE extends MessageContentType.Image>
            extends MessageHolders.BaseOutcomingMessageViewHolder<MESSAGE>{
//onBind() and other methods here
}
```

This mirrors the static class `OutcomingImageMessageViewHolder` in ChatKits `MessageHolders`, which looks like the following:
```
public static class OutcomingImageMessageViewHolder<MESSAGE extends MessageContentType.Image>
            extends BaseOutcomingMessageViewHolder<MESSAGE> {
//methods here
}
```

but when I try and pass my 'created from scratch' version of this class to 
` MessageHolders holdersConfig = new MessageHolders().setOutcomingImageConfig()`
I get the error:
`Error:(108, 75) error: incompatible types: Class<ChatOutcomingTextMessageViewHolder> cannot be converted to Class<? extends BaseMessageViewHolder<? extends IMessage>>`

But as far as I can see, they are identical class signatures?
Has anybody created a view holder completely from scratch? As I am not sure of how to define the class to allow me to do so!

**Comment by kirvis250** [comment]
MESSAGE extends MessageContentType.Image instead of MESSAGE extends IMessage.

**Comment by CallumCoombes** [comment]
What do you mean? I already use `MESSAGE extends MessageContentType.Image`?

**Comment by CallumCoombes** [comment]
Got it working completely from scratch. What I should have been doing is creating TWO classes, one with base inheritance and one which inherits from this.
For example:

Base Inheritance class - 
```
public class CustomBaseOutcomingImageMessageViewHolder<MESSAGE extends MessageContentType.Image>
        extends MessageHolders.BaseOutcomingMessageViewHolder<MESSAGE> {

    protected ImageView image;
    protected View imageOverlay;
    protected TextView username;

    public CustomChatOutcomingImageMessageViewHolder(View itemView) {
        super(itemView);
        image = (ImageView) itemView.findViewById(com.stfalcon.chatkit.R.id.image);
        imageOverlay = itemView.findViewById(com.stfalcon.chatkit.R.id.imageOverlay);
        username = (TextView) itemView.findViewById(com.stfalcon.chatkit.R.id.messageUserName);
    }

    @Override
    public void onBind(MESSAGE message) {
        super.onBind(message);

        if (username != null) {
            username.setText(message.getUser().getName());
        }
    }

    @Override
    public final void applyStyle(MessagesListStyle style) {
        super.applyStyle(style);

        if (username != null) {
            username.setTextColor(Color.parseColor("#000000"));
            username.setTypeface(null, Typeface.BOLD);
            username.setGravity(Gravity.BOTTOM);
        }
    }
}
```

Subclass of the above class - 

```
public class ChatOutcomingImageMessageViewHolder extends CustomChatOutcomingImageMessageViewHolder<Message> {

    //Anymore custom fields

    public ChatOutcomingImageMessageViewHolder(View itemView) {
        super(itemView);
        //initialise any custom fields
    }

    @Override
    public void onBind(Message message) {
        super.onBind(message);
        //Do anymore custom on bind stuff here
    }
}
```

Now I can pass the above custom viewholder `ChatOutcomingImageMessageViewHolder` (and a custom layout) to ChatKit like so - 
```
 MessageHolders holdersConfig = new MessageHolders()
                .setOutcomingImageConfig(ChatOutcomingImageMessageViewHolder.class, R.layout.item_custom_outcoming_image_message)
```

This then allowed me to bypass view holder implementation in ChatKit itself and handle things such as image loading in my own way. Hopefully this helps out others who run into this issue!
