### ISSUE TITLE
Ordering dialogs

### ISSUE THREAD

**Issue by enzonotario** [stfalcon-studio/ChatKit#8]
Hi! 
I'm new on android development... I'm using this library and is amazing!, it works perfectly, but now I want to keep the dialog list ordered by last messages.
My problem is not the SQL query or how can I get the List<Dialog> ordered, but how can I set the order in this library (I think that it gets ordered by seeing the lastMessage's createdAt, but seems that not)...

Can you help me, please?

Thanks!

**Comment by PedroBarbosaPT** [comment]
If i'm not mistaken, it gets ordered by the order you insert the messages, using addToStart, ordering as nothing to do with createdAt field.
Just load the messages by order and add them one by one, from the oldest to the newest

**Comment by enzonotario** [comment]
Sorry, but I'm talking about the DialogsList...

I don't speak english so maybe you understand me... I want to keep the dialogs list ordered all the time (I'm using websockets so the order can change, but I'm also using EventBus, if it is needed)

Thanks!

**Comment by mradzinski** [comment]
I haven't seen a proper way of achieving this nor I tried, but from the top of my head, a way around the limitation probably would be to first delete the dialog by invoking ```adapter.deleteById(String id)``` and then re-add it at the top of the adapter. As per the documentation this can be achieved by invoking ```adapter.addItem(int position, DIALOG dialog``` where ```position``` indicates the position of the new dialog.

**Comment by enzonotario** [comment]
Thanks! but I moved to my own implementation of RecyclerView since I need a much simply and "focused case" implementation... Throw it's an amazing library! I'll close this issue...
