### ISSUE TITLE
How to add Data in Dialog 

### ISSUE THREAD

**Issue by ibmshaikh** [stfalcon-studio/ChatKit#83]
I have data to add in Arraylist. But How to add that data. How to use that adapter.addItems(List items).

**Comment by jirevwe** [comment]
Can you a give better a description?

**Comment by ibmshaikh** [comment]
please jirevwe give your Email or Whatsapp number to discuss the problem Please. I m stuck.

**Comment by jirevwe** [comment]
@ibmshaikh rtukpe@gmail.com

**Comment by ibmshaikh** [comment]
thank you so much @jirevwe
