### ISSUE TITLE
Don't found way to do setText in MessageInput.

### ISSUE THREAD

**Issue by chnouman** [stfalcon-studio/ChatKit#84]
Hy sorry i'm using messageInput as input field when someone write something and press send button the data goes off according to my condition i want to set text in message input kindly help me i'm unable to find setText method.

**Comment by chnouman** [comment]
@stfalcon dear

**Comment by martykan** [comment]
`messageInput.getInputEditText().setText("anything");`

**Comment by chnouman** [comment]
thanks @martykan i'll try this.
