### ISSUE TITLE
Can you provide the Xamarin library version?

### ISSUE THREAD

**Issue by jingliancui** [stfalcon-studio/ChatKit#87]
Hello , I am a c#/dotnet developer,I try to transfer your library to the Xamarin.Android binding library.
But after I finished the binding ,it will throw error in my xamarin android app.
Can you provide the Xamarin library version?

**Comment by Xenophile426** [comment]
yes please

**Comment by alexkrolinfinum** [comment]
If you have a time - feel free to implement your solution for this, we'll be happy to share your version in README

**Comment by troy379** [comment]
If you have a time - feel free to implement your own solution for this, we'll be happy to share your version in README
