### ISSUE TITLE
MessagesListAdapter.clear() does not call notifyDataSetChanged()

### ISSUE THREAD

**Issue by vitaliyrd** [stfalcon-studio/ChatKit#89]
This causes crashes when adding new data, especially if you were using custom ViewHolders.

**Comment by zymartinez** [comment]
yep, I ended up having to manually call `notifyDataSetChanged()` to the adapter instance every time `clear()` is called. Its a mild inconvenience and a bit confusing.

**Comment by bevzaanton** [comment]
Oh, yeah, we have missed it. Thanks! I fixed it in version 0.3.0.

**Comment by bevzaanton** [comment]
One tiny fix. We added separate method `clear(boolean notifyDataSetChanged)`. It can be useful if you want to add messages immediately after clearing. Method `clear()` does `notifyDataSetChanged` by default.
