### ISSUE TITLE
Show Location in Map - MessageList

### ISSUE THREAD

**Issue by ulaserdegor** [stfalcon-studio/ChatKit#91]
Hi,
In the screenshot, the message type is shown as a map. But I did not find such a possibility in the code part. Does anyone have information?

![image](https://user-images.githubusercontent.com/12948351/30531205-53685cb2-9c55-11e7-8dac-25145857106c.png)

**Comment by JackJ8se** [comment]
Did you find anything related to this issue?

**Comment by bevzaanton** [comment]
You can check this issue #116
