### ISSUE TITLE
Time Change in Messages

### ISSUE THREAD

**Issue by rlee1990** [stfalcon-studio/ChatKit#94]
Is there a way to change the formate to a 12 hour format in each message?

**Comment by andreluizreis** [comment]
I think it is not possible because the setTime method expects to receive a Date object.

**Comment by rlee1990** [comment]
A date object can be in a 12 hour format

**Comment by andreluizreis** [comment]
@rlee1990 Can you show me an example? 
How can you solve this?
chatMessage.setCreatedAt(new Date());

**Comment by rlee1990** [comment]
I am not refering to in the object I am referring to the formatting of the date on each message.

**Comment by andreluizreis** [comment]
You told me: "A date object can be in a 12 hour format". Can you show me how a date object can be in a 12-hour format?

**Comment by rlee1990** [comment]
When you make it a string using simpleDateFormatter. Im not at the computer to really type an example but stackoverflow has some good ones

**Comment by andreluizreis** [comment]
I tried already with SimpleDateFormatter. You need to pass a Date Object at the end and it will continue to show 24 hours format because of that.

**Comment by rlee1990** [comment]
I know that thats why I posted this issue thread.

**Comment by andreluizreis** [comment]
You need to create a View Holder to `OutcomingTextMessage` and `IncomingTextMessage`.
Inside the class you have override the method `onBind`. There, you receive the chatMessage object. You can get the date from there and format to AM, PM. After that you do messageTimeTextView.setText(newTime).
